import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { parseActivityProgramPdf } from './activity-program-parser.js'

const fixture = process.argv[2]
if (!fixture) throw new Error('Pass the Activity Program PDF path as the first argument.')
const parsed = await parseActivityProgramPdf(new Uint8Array(await readFile(fixture)))
assert.equal(parsed.reportDate, '2026-08-31')
assert.equal(parsed.bookings.length, 45)
assert.equal(parsed.bookings.reduce((sum, booking) => sum + (booking.covers || 0), 0), 122)
const arithmeticOverride = parsed.bookings.find(booking => booking.bookingNumber === '2654375')
assert.deepEqual({ covers: arithmeticOverride?.covers, adults: arithmeticOverride?.coverResolution?.adults, kids: arithmeticOverride?.coverResolution?.kids, source: arithmeticOverride?.coverResolution?.source }, { covers: 3, adults: 2, kids: 1, source: 'arithmetic_expression' })
assert.equal(parsed.bookings.filter(booking => booking.sourceStatus.toLowerCase() === 'confirmed').length, 44)
assert.equal(parsed.bookings.filter(booking => booking.sourceStatus.toLowerCase() === 'pending').length, 1)
assert.deepEqual(parsed.bookings.find(booking => booking.bookingNumber === '2654179')?.rooms, ['211', '212', '213'])
assert.deepEqual(parsed.bookings.find(booking => booking.bookingNumber === '2652703')?.rooms, ['255', '256', '257'])
assert.equal(parsed.bookings.find(booking => booking.bookingNumber === '2652695')?.reservationTime, '18:30')
assert.equal(parsed.bookings.find(booking => booking.bookingNumber === '2605721')?.reservationTime, '19:30')
assert.equal(parsed.bookings.find(booking => booking.bookingNumber === '2650767')?.reservationTime, '21:00')
assert.equal(parsed.bookings.find(booking => booking.bookingNumber === '2577912')?.readiness, 'REVIEW_REQUIRED')
assert(parsed.bookings.some(booking => booking.walkIn))
assert.equal(parsed.bookings.find(booking => booking.bookingNumber === '2654213')?.bookedBy, 'Aigerim Rakhym')
assert.equal(parsed.bookings.find(booking => booking.bookingNumber === '2633039')?.primaryGuest, 'Diego Antonio Arrabal Maldonado')
assert(/cancel Kaage/i.test(parsed.bookings.find(booking => booking.bookingNumber === '2653114')?.sourceNotes || ''))
const annotated = parsed.bookings.find(booking => booking.bookingNumber === '2650116')
const annotatedText = [annotated?.sourceNotes, ...(annotated?.guestMembers.map(guest => guest.guestNotes) || [])].join(' ')
assert(/G:/i.test(annotatedText), annotatedText)
assert(/B:/i.test(annotatedText), annotatedText)
assert(parsed.bookings.every(booking => !/Page \d+ from/i.test(booking.bookedBy)))
assert(parsed.validation.reconciled)
assert(parsed.validation.messages.some(message => /raw section headers declare 121/i.test(message)))
console.log(JSON.stringify({ bookings: parsed.bookings.length, covers: parsed.bookings.reduce((sum, booking) => sum + (booking.covers || 0), 0), confirmed: parsed.bookings.filter(booking => booking.sourceStatus.toLowerCase() === 'confirmed').length, pending: parsed.bookings.filter(booking => booking.sourceStatus.toLowerCase() === 'pending').length, reviewRequired: parsed.bookings.filter(booking => booking.readiness === 'REVIEW_REQUIRED').length }, null, 2))
