import assert from 'node:assert/strict'
import { createHash, randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'
import { BillTipFinalizationService } from './bill-tip-finalization-service.js'
import { compareOperationalFingerprints, createMigrationFingerprint, runMigrations, migrationStatus, runPreflight } from './migration-store.js'
import { ANDALUCIA_SCOPE_ID } from './outlet-membership-repository.js'
import { AuthorizationService } from './authorization-service.js'

const rollbackDb=new PGlite()
await rollbackDb.exec(await readFile('database/schema.sql','utf8'))
await assert.rejects(()=>runMigrations(rollbackDb,{simulateFailureVersion:'012'}),/SIMULATED_MIGRATION_FAILURE:012/)
assert.equal((await migrationStatus(rollbackDb)).migrations.find(item=>item.version==='012')?.state,'pending')
assert.equal((await rollbackDb.query<{present:boolean}>("select exists(select 1 from information_schema.columns where table_name='bill_tip_distributions' and column_name='version_number') present")).rows[0].present,false)
assert.equal((await runPreflight(rollbackDb,'isolated-rehearsal')).status,'READY')
const rehearsalBefore=await createMigrationFingerprint(rollbackDb);await runMigrations(rollbackDb);const rehearsalAfter=await createMigrationFingerprint(rollbackDb)
assert.equal(compareOperationalFingerprints(rehearsalBefore,rehearsalAfter).preserved,true);assert.equal((await migrationStatus(rollbackDb)).migrations.find(item=>item.version==='012')?.state,'applied')
await rollbackDb.close()

const db=new PGlite()
try{
  await db.exec(await readFile('database/schema.sql','utf8'));await runMigrations(db)
  assert.equal((await migrationStatus(db)).migrations.find(item=>item.version==='012')?.state,'applied')
  const ownerId=randomUUID();await db.query("insert into user_accounts(id,login_identifier,normalized_login_identifier,display_name,password_hash,status) values($1,'finalizer','finalizer','Finalizer Owner','unused','active')",[ownerId]);await db.query("insert into authorization_user_roles(id,user_id,role_id,active) select $1,$2,id,true from authorization_roles where role_key='owner'",[randomUUID(),ownerId])
  const authorization=new AuthorizationService(db),summary=await authorization.authorizationForUser(ownerId),owner={userId:ownerId,sessionId:randomUUID(),loginIdentifier:'finalizer',displayName:'Finalizer Owner',staffId:null,...summary};await authorization.requireOutletPermission(owner,'manage_bill_tips',ANDALUCIA_SCOPE_ID)
  await db.query("insert into configuration_options(id,group_key,value,label,metadata,active,sort_order) values($1,'duty_codes','on','ON',$2,true,0),($3,'duty_codes','al','AL',$4,true,1)",[randomUUID(),JSON.stringify({displayCode:'ON',dutyClassification:'working',billTipEligible:true}),randomUUID(),JSON.stringify({displayCode:'AL',dutyClassification:'annualLeave',billTipEligible:false})])
  const revision1=randomUUID();await db.query("insert into staff_membership_baseline_reviews(id,outlet_scope_id,baseline_month,status,revision_number,review_type,is_current_revision,is_authoritative,approved_at,approved_by,approved_by_user_id) values($1,$2,'2026-08','approved',1,'initial',true,true,now(),$3,$4)",[revision1,ANDALUCIA_SCOPE_ID,'Finalizer Owner',ownerId])
  const staffIds=[randomUUID(),randomUUID()];for(let i=0;i<2;i++){await db.query("insert into staff(id,staff_number,full_name,position_key,employment_status_key,join_date) values($1,$2,$3,'Waiter','active','2026-01-01')",[staffIds[i],`F${i+1}`,`Final Staff ${i+1}`]);await db.query("insert into staff_membership_history(id,staff_id,outlet_scope_id,membership_dimension,effective_from,effective_to,source,review_status,reviewed_at,reviewed_by,baseline_revision_id,is_current_baseline) values($1,$2,$3,'regular_outlet','2026-08-01','2026-08-31','baseline_manager_review','approved',now(),'Finalizer',$4,true)",[randomUUID(),staffIds[i],ANDALUCIA_SCOPE_ID,revision1])}
  const service=new BillTipFinalizationService(db,()=> '2026-09-11'),context={outletScopeId:ANDALUCIA_SCOPE_ID,actor:owner},external=[{id:'support-1',name:'Support Colleague',staffReference:'EXT-1',departmentOutlet:'Guest Services',fixedAmount:'10.00',remarks:'Approved support'}]
  await assert.rejects(()=>new BillTipFinalizationService(db,()=> '2026-08-15').finalizeInitial({month:'2026-08',totalPool:'100.00',externalAllocations:external,idempotencyKey:'open-1'},context),/still in progress/i)
  await assert.rejects(()=>service.finalizeInitial({month:'2026-08',totalPool:'100.00',externalAllocations:external,idempotencyKey:'blocked-1'},context),/blockers/i)
  for(const staffId of staffIds)for(let day=1;day<=31;day++)await db.query('insert into duty_roster_entries(id,staff_id,duty_date,duty_code_value) values($1,$2,$3,$4)',[randomUUID(),staffId,`2026-08-${String(day).padStart(2,'0')}`,staffId===staffIds[0]&&day===1?'al':'on'])
  const initialRace=await Promise.allSettled(['finalize-v1','finalize-v1-race'].map(idempotencyKey=>service.finalizeInitial({month:'2026-08',totalPool:'100.00',externalAllocations:external,idempotencyKey},context)));assert.equal(initialRace.filter(x=>x.status==='fulfilled').length,1);const v1=(initialRace.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof service.finalizeInitial>>>).value;const winningFinalizeKey=(await db.query<any>('select finalization_key from bill_tip_distributions where id=$1',[v1!.id])).rows[0].finalization_key;assert.equal(v1?.version,1);assert.equal(v1?.status,'finalized');assert.equal(v1?.isCurrent,true);assert.equal(v1?.membershipRevisionId,revision1);assert.equal(v1?.finalizedByUserId,ownerId);assert.equal(v1?.reconciliation,'100.00')
  assert.equal((await service.finalizeInitial({month:'2026-08',totalPool:'100.00',externalAllocations:external,idempotencyKey:winningFinalizeKey},context))?.id,v1?.id)
  const v1Rows=JSON.stringify({distribution:(await db.query<any>('select * from bill_tip_distributions where id=$1',[v1!.id])).rows,staff:(await db.query<any>('select * from bill_tip_staff_allocations where distribution_id=$1 order by staff_id',[v1!.id])).rows,external:(await db.query<any>('select * from bill_tip_manual_allocations where distribution_id=$1 order by id',[v1!.id])).rows});const v1Digest=createHash('sha256').update(v1Rows).digest('hex')
  await assert.rejects(()=>db.query("update bill_tip_distributions set pool_amount=999 where id=$1",[v1!.id]),/immutable/i);await assert.rejects(()=>db.query('delete from bill_tip_staff_allocations where distribution_id=$1',[v1!.id]),/immutable/i);await assert.rejects(()=>service.reopen(v1!.id,'  ','correction-empty',context),/reason/i)
  const correctionRace=await Promise.allSettled(['correction-v2','correction-v2-race'].map(key=>service.reopen(v1!.id,'Correct approved pool',key,context)));assert.equal(correctionRace.filter(x=>x.status==='fulfilled').length,1);const v2=(correctionRace.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof service.reopen>>>).value;const winningCorrectionKey=(await db.query<any>('select correction_key from bill_tip_distributions where id=$1',[v2!.id])).rows[0].correction_key;assert.equal(v2?.version,2);assert.equal(v2?.status,'correction_in_review');assert.equal(v2?.previousVersionId,v1?.id);assert.equal((await service.reopen(v1!.id,'Correct approved pool',winningCorrectionKey,context))?.id,v2?.id)
  await assert.rejects(()=>service.reopen(v1!.id,'Concurrent duplicate','correction-v2-other',context),/already in review/i)
  const beforeDiff=await service.diff(v2!.id);assert.equal(beforeDiff?.totalPool.before,'100.00');assert.equal(beforeDiff?.totalPool.after,'100.00')
  await db.query("update duty_roster_entries set duty_code_value='al' where staff_id=$1 and duty_date='2026-08-02'",[staffIds[1]])
  const correctionInput={month:'2026-08',totalPool:'120.00',externalAllocations:[{...external[0],fixedAmount:'20.00'}],idempotencyKey:'finalize-v2'};const refinalizeRace=await Promise.allSettled([service.refinalize(v2!.id,correctionInput,context),service.refinalize(v2!.id,correctionInput,context)]);assert(refinalizeRace.some(x=>x.status==='fulfilled'));assert.equal((await db.query<{count:number}>("select count(*)::int count from audit_logs where entity_type='bill_tip_distribution' and entity_id=$1 and action='correction_finalized'",[v2!.id])).rows[0].count,1);const finalizedV2=await service.version(v2!.id);assert.equal(finalizedV2?.status,'finalized');assert.equal(finalizedV2?.isCurrent,true)
  const history=await service.history('2026-08',ANDALUCIA_SCOPE_ID);assert.deepEqual(history.map(x=>[x?.version,x?.status,x?.isCurrent]),[[2,'finalized',true],[1,'superseded',false]])
  assert.equal((await service.refinalize(v2!.id,{month:'2026-08',totalPool:'120.00',externalAllocations:[],idempotencyKey:'retry'},context))?.id,v2?.id)
  const afterDiff=await service.diff(v2!.id);assert.deepEqual(afterDiff?.totalPool,{before:'100.00',after:'120.00'});assert.deepEqual(afterDiff?.external,{before:'10.00',after:'20.00'});assert.notEqual(afterDiff?.staff.find(x=>x.staffId===staffIds[1])?.before,afterDiff?.staff.find(x=>x.staffId===staffIds[1])?.after)
  const v1After=JSON.stringify({distribution:(await db.query<any>('select * from bill_tip_distributions where id=$1',[v1!.id])).rows,staff:(await db.query<any>('select * from bill_tip_staff_allocations where distribution_id=$1 order by staff_id',[v1!.id])).rows,external:(await db.query<any>('select * from bill_tip_manual_allocations where distribution_id=$1 order by id',[v1!.id])).rows});assert.equal(JSON.parse(v1After).distribution[0].status,'superseded');const normalized=(value:string)=>{const parsed=JSON.parse(value);delete parsed.distribution[0].status;delete parsed.distribution[0].is_current;delete parsed.distribution[0].updated_at;delete parsed.distribution[0].updated_by;return parsed};assert.deepEqual(normalized(v1After),normalized(v1Rows))
  assert.equal((await db.query<{count:number}>("select count(*)::int count from bill_tip_distributions where outlet_scope_id=$1 and distribution_month='2026-08' and is_current=true",[ANDALUCIA_SCOPE_ID])).rows[0].count,1)
  console.log(JSON.stringify({migration:'012',version1:true,immutable:true,version2:true,history:true,idempotent:true,initialConcurrency:true,correctionConcurrency:true,refinalizationConcurrency:true,singleCurrent:true,correctionDiff:true,reconciliation:[v1?.reconciliation,finalizedV2?.reconciliation],snapshotDigest:v1Digest},null,2))
}finally{await db.close()}
