import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'
import { ACTIVITY_PROGRAM_PARSER_VERSION, parseActivityProgramPdf } from './activity-program-parser.js'
import { BookingRepository } from './booking-repository.js'
import { syntheticActivityProgramPdf } from './activity-program-test-fixture.js'

const pdf = Buffer.from(syntheticActivityProgramPdf('import'))
const parsed = await parseActivityProgramPdf(new Uint8Array(pdf))
const db = new PGlite()
await db.exec(await readFile('database/schema.sql', 'utf8'))
const repository = new BookingRepository(db)
await repository.initialize()
const previewInput = { fileName: '2026-09-01_02-04_daily_bookings_report.pdf', fileHash: createHash('sha256').update(pdf).digest('hex'), reportDate: parsed.reportDate, parserVersion: ACTIVITY_PROGRAM_PARSER_VERSION, summary: { bookingGroups: parsed.bookings.length, totalCovers: parsed.bookings.reduce((total, booking) => total + (booking.covers || 0), 0), confirmed: parsed.bookings.filter(booking => booking.sourceStatus.toLowerCase() === 'confirmed').length, pending: parsed.bookings.filter(booking => booking.sourceStatus.toLowerCase() === 'pending').length, warnings: parsed.bookings.filter(booking => booking.warnings.length > 0).length, possibleDuplicates: 0 }, validation: parsed.validation, bookings: parsed.bookings }
const preview = await repository.prepareImportPreview(previewInput)
const readyIndexes = preview.bookings.map((booking, index) => booking.readiness === 'READY' ? index : -1).filter(index => index >= 0)
assert.equal(readyIndexes.length, 3)
assert.equal(preview.bookings.filter(booking => booking.readiness === 'REVIEW_REQUIRED').length, 1)
const imported = await repository.confirmImport(preview.batchId, readyIndexes)
assert.equal(imported.importedBookings, 3)
assert.equal(imported.importedCovers, 6)
assert.equal(imported.skippedReviewRecords, 1)
const live = await repository.list('2026-08-31')
assert.equal(live.length, 3)
assert.equal(live.reduce((total, booking) => total + booking.covers, 0), 6)
assert(live.every(booking => booking.bookingSource === 'activity_program' && booking.importedBatchId))
const multiRoom = live.find(booking => booking.bookingNumber === '9000001')
assert(multiRoom)
assert.equal(multiRoom.roomNumber, '211, 212')
assert.equal(multiRoom.covers, 3)
assert.equal((await repository.guestMembers(multiRoom.id)).length, 2)
const waiterId = '00000000-0000-4000-8000-000000000099'
await db.query('insert into staff (id, staff_number, full_name, position_key, employment_status_key, join_date) values ($1,$2,$3,$4,$5,$6)', [waiterId, 'AND-T99', 'Import Test Waiter', 'Waiter', 'active', '2026-01-01'])
const assigned = await repository.save({ ...multiRoom, tableNumber: 'T01', waiterId, waiter: null, bookingStatus: 'arrived' })
assert.equal(assigned.tableNumber, 'T01')
assert.equal(assigned.waiterId, waiterId)
assert.equal(assigned.bookingStatus, 'arrived')
const noShowTarget = live.find(booking => booking.bookingNumber === '9000002')
assert(noShowTarget)
await repository.save({ ...noShowTarget, bookingStatus: 'no_show' })
const repeatedPreview = await repository.prepareImportPreview(previewInput)
assert.equal(repeatedPreview.bookings.filter(booking => booking.readiness === 'DUPLICATE').length, 3)
const repeated = await repository.confirmImport(repeatedPreview.batchId, readyIndexes)
assert.equal(repeated.importedBookings, 0)
assert.equal(repeated.skippedDuplicates, 3)
const preserved = await repository.find(multiRoom.id)
assert.equal(preserved?.tableNumber, 'T01')
assert.equal(preserved?.waiterId, waiterId)
assert.equal(preserved?.bookingStatus, 'arrived')
const dashboard = await repository.summary('2026-08-31')
assert.equal(dashboard.totalBookings, 3)
assert.equal(dashboard.expectedCovers, 4)
assert.equal(dashboard.arrived, 1)
assert.equal(dashboard.arrivedCovers, 3)
assert.equal(dashboard.remainingBookings, 1)
assert.equal(dashboard.remainingCovers, 1)
assert.equal(dashboard.noShows, 1)
assert.equal(dashboard.unassignedTables, 1)
assert.equal(dashboard.unassignedWaiters, 1)
console.log(JSON.stringify({ importedBookings: imported.importedBookings, importedCovers: imported.importedCovers, guestMembers: (await repository.guestMembers(multiRoom.id)).length, duplicateReimportSkipped: repeated.skippedDuplicates, tableAndWaiterPreserved: true, dashboard }, null, 2))
