import type { PGlite } from '@electric-sql/pglite'
import type { AuthPrincipal, MonthlyReportDay, MonthlyReportView } from '../src/domain.js'
import { addCalendarMonths, calendarDates, monthRange, serviceDate } from '../src/service-date.js'
import { DailyReportSnapshotRepository, type DailyReportFrozenPayload } from './daily-report-snapshot-repository.js'
import { MonthlyReportInputRepository, monthlyFinanceComplete, type MonthlyFinancePayload } from './monthly-report-input-repository.js'
import { ReportingRepository } from './reporting-repository.js'

const cents=(value:unknown)=>Math.round(Number(value||0)*100), amount=(value:number)=>(value/100).toFixed(2), round2=(value:number)=>Number(value.toFixed(2))
const revenueKeys=['foodRevenue','beverageRevenue','wineRevenue','liquorRevenue','totalSale','totalDiscount','totalVoid','netSale','totalRevenue'] as const
const categoryDefaults=[['honeymoon','Honeymoon'],['birthday','Birthday'],['anniversary','Anniversary'],['seeYouSoon','See You Soon'],['vip','VIP'],['tlc','TLC'],['siyamFamily','Repeaters / Siyam Family'],['famtrip','Famtrip'],['presstrip','Presstrip']] as const
const validMonth=(value:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(value)
const matched=(entered:string|null,calculated:string|null)=>entered===null||calculated===null?null:Math.abs(Number(entered)-Number(calculated))<=0.0001
const labelKey=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,value=>value.toUpperCase())

export class MonthlyReportService {
  private readonly snapshots:DailyReportSnapshotRepository
  private readonly inputs:MonthlyReportInputRepository
  constructor(private readonly db:PGlite,private readonly reporting:ReportingRepository,private readonly todayProvider=serviceDate){this.snapshots=new DailyReportSnapshotRepository(db);this.inputs=new MonthlyReportInputRepository(db)}

  private aggregate(rows:Array<{serviceDate:string;frozenPayload:DailyReportFrozenPayload}>){
    const totals={totalCovers:0,totalBookings:0,totalKids:0,arrivedCovers:0,noShowCovers:0,walkIns:0,doubleDinePax:0,averageCoversPerServiceNight:0}
    const revenueCents:Record<string,number>={foodRevenue:0,beverageRevenue:0,wineRevenue:0,liquorRevenue:0,totalSale:0,totalDiscount:0,totalVoid:0,netSale:0,totalRevenue:0}
    const items=new Map<string,{quantity:number;revenue:number}>(),sellers=new Map<string,number>(),occasions=new Map<string,{key:string;label:string;count:number;covers:number}>(categoryDefaults.map(([key,label])=>[key,{key,label,count:0,covers:0}]))
    let chargeable=0,wineSpirits=0,itemsSold=0;const variances:MonthlyReportView['variances']=[]
    for(const row of rows){const c=row.frozenPayload;totals.totalCovers+=c.servicePerformance.totalCovers;totals.totalBookings+=c.servicePerformance.totalBookings;totals.totalKids+=c.servicePerformance.kids;totals.arrivedCovers+=c.servicePerformance.arrivedCovers;totals.noShowCovers+=c.servicePerformance.noShowCovers;totals.walkIns+=c.servicePerformance.walkIns;totals.doubleDinePax+=Number(c.serviceVerification.doubleDinePax||0)
      for(const key of revenueKeys)revenueCents[key]+=cents(c.symphony[key])
      for(const detail of c.upselling.details||[]){const d=detail as Record<string,unknown>,label=String(d.item||'Unspecified'),seller=String(d.soldBy||''),value=cents(d.amount),quantity=Number(d.quantity||0);itemsSold+=quantity;if(d.source==='Wine / Spirits')wineSpirits+=value;else chargeable+=value;const item=items.get(label)||{quantity:0,revenue:0};item.quantity+=quantity;item.revenue+=value;items.set(label,item);if(seller&&seller!=='Unassigned')sellers.set(seller,(sellers.get(seller)||0)+value)}
      for(const raw of c.guestOccasions.categories){const category=raw as Record<string,unknown>,key=String(category.key),current=occasions.get(key)||{key,label:String(category.label),count:0,covers:0};current.count+=Number(category.count||0);current.covers+=Number(category.covers||0);occasions.set(key,current)}
      const v=c.revenueVerification;if(v?.acknowledged&&v.netSale&&v.totalRevenue&&v.difference&&Math.abs(Number(v.difference))>0)variances.push({date:row.serviceDate,netSale:v.netSale,totalRevenue:v.totalRevenue,difference:v.difference,verifiedBy:v.verifiedByName||'Authenticated manager',verifiedAt:v.verifiedAt||''})
    }
    totals.averageCoversPerServiceNight=rows.length?round2(totals.totalCovers/rows.length):0
    const topItems=[...items].map(([label,v])=>({label,quantity:v.quantity,revenue:amount(v.revenue)})).sort((a,b)=>b.quantity-a.quantity||Number(b.revenue)-Number(a.revenue)),topSellers=[...sellers].map(([label,revenue])=>({label,revenue:amount(revenue)})).sort((a,b)=>Number(b.revenue)-Number(a.revenue))
    return{totals,revenue:Object.fromEntries(Object.entries(revenueCents).map(([key,value])=>[key,amount(value)])) as MonthlyReportView['revenue'],variances,upselling:{totalRevenue:amount(chargeable+wineSpirits),itemsSold,chargeableRevenue:amount(chargeable),wineSpiritsRevenue:amount(wineSpirits),topItem:topItems[0]?.label||'—',topSeller:topSellers[0]?.label||'—',topItems:topItems.slice(0,3),topSellers:topSellers.slice(0,3)},occasions:[...occasions.values()]}
  }

  private async staffing(start:string,end:string){
    const currentTeamSize=Number((await this.db.query<{count:number}>("select count(*)::int count from staff s join configuration_options c on c.group_key='employment_statuses' and c.value=s.employment_status_key where coalesce(c.metadata->>'employmentStage','active')='active'")).rows[0]?.count||0)
    const rows=(await this.db.query<{classification:string;count:number}>("select coalesce(c.metadata->>'dutyClassification','other') classification,count(*)::int count from duty_roster_entries r left join configuration_options c on c.group_key='duty_codes' and c.value=r.duty_code_value where r.duty_date between $1 and $2 group by 1",[start,end])).rows
    const value=(key:string)=>Number(rows.find(row=>row.classification===key)?.count||0),days=calendarDates(start,end).length
    return{currentTeamSize,averageOnDuty:days?round2(value('working')/days):0,offDays:value('off'),annualLeaveDays:value('annualLeave'),publicHolidays:value('publicHoliday'),sickLeaveDays:value('sickLeave')}
  }

  async view(month:string,outlet:{id:string;scopeKey:string;displayName:string}):Promise<MonthlyReportView>{
    if(!validMonth(month))throw new Error('MONTHLY_REPORT_MONTH_INVALID');const [monthStart,monthEnd]=monthRange(`${month}-01`),today=this.todayProvider(),dates=calendarDates(monthStart,monthEnd),effectiveEnd=monthEnd<today?monthEnd:today<monthStart?monthStart:today
    const snapshots=(await this.snapshots.currentApprovedSnapshots(outlet.id,monthStart,monthEnd)).filter(row=>row.serviceDate<=today),byDate=new Map(snapshots.map(row=>[row.serviceDate,row])),currentRows=(await this.db.query<any>('select id,service_date::text,status from daily_reports where outlet_scope_id=$1 and service_date between $2 and $3 and is_current_authority=true',[outlet.id,monthStart,monthEnd])).rows,reports=new Map(currentRows.map((row:any)=>[row.service_date,row]))
    const days:MonthlyReportDay[]=dates.map(date=>{const snapshot=byDate.get(date);if(snapshot){const c=snapshot.frozenPayload;return{date,status:'approved',reportId:snapshot.dailyReportId,covers:c.servicePerformance.totalCovers,bookings:c.servicePerformance.totalBookings,kids:c.servicePerformance.kids,arrivedCovers:c.servicePerformance.arrivedCovers,noShowCovers:c.servicePerformance.noShowCovers,walkIns:c.servicePerformance.walkIns,doubleDinePax:Number(c.serviceVerification.doubleDinePax||0)}}const report=reports.get(date);return{date,status:report?.status==='draft'?'draft':report?.status==='reviewed'?'reviewed':date>today?'not-yet-closed':date===today?'in-progress':'missing-report',reportId:report?.id||null,covers:null,bookings:null,kids:null,arrivedCovers:null,noShowCovers:null,walkIns:null,doubleDinePax:null}})
    const aggregate=this.aggregate(snapshots),expectedDays=monthStart>today?0:dates.filter(date=>date<=today).length,approvedDays=snapshots.length,current=monthStart<=today&&monthEnd>=today,state=approvedDays===dates.length?'complete':current?'in-progress':approvedDays?'partial':'no-approved-data',label=state==='complete'?'OPERATIONS COMPLETE':state==='in-progress'?'MONTH IN PROGRESS':state==='partial'?'PARTIAL MONTH':'NO APPROVED DATA'
    const approved=days.filter(day=>day.status==='approved'),highest=(low=false)=>[...approved].sort((a,b)=>(low?1:-1)*(Number(a.covers)-Number(b.covers))||a.date.localeCompare(b.date))[0]?.date||null,busiest=[...approved].sort((a,b)=>Number(b.bookings)-Number(a.bookings))[0]?.date||null
    const operational=await this.reporting.report('month',monthStart,effectiveEnd),staffing=await this.staffing(monthStart,effectiveEnd),input=await this.inputs.get(outlet.id,monthStart),payload=input?.financePayload
    const previousMonthStart=addCalendarMonths(monthStart,-1),previousMonthEnd=monthRange(previousMonthStart)[1],previousRows=await this.snapshots.currentApprovedSnapshots(outlet.id,previousMonthStart,previousMonthEnd),previous=this.aggregate(previousRows),previousInput=await this.inputs.get(outlet.id,previousMonthStart),occasionCount=aggregate.occasions.reduce((sum,row)=>sum+row.count,0),previousOccasions=previous.occasions.reduce((sum,row)=>sum+row.count,0)
    const compare=(key:string,label:string,a:number,b:number)=>({key,label,current:a,previous:b,difference:round2(a-b),changePercent:b?round2((a-b)/Math.abs(b)*100):a?null:0}),comparisonAvailable=approvedDays>0&&previousRows.length>0,financeAvailable=Boolean(input&&previousInput&&input.financeStatus.startsWith('verified')&&previousInput.financeStatus.startsWith('verified'))
    const currentNoShowRate=aggregate.totals.totalCovers?round2(aggregate.totals.noShowCovers/aggregate.totals.totalCovers*100):0,previousNoShowRate=previous.totals.totalCovers?round2(previous.totals.noShowCovers/previous.totals.totalCovers*100):0
    const comparisonMetrics=comparisonAvailable?[
      compare('covers','Total Covers',aggregate.totals.totalCovers,previous.totals.totalCovers),compare('averageCovers','Average Covers',aggregate.totals.averageCoversPerServiceNight,previous.totals.averageCoversPerServiceNight),compare('bookings','Total Bookings',aggregate.totals.totalBookings,previous.totals.totalBookings),compare('kids','Kids',aggregate.totals.totalKids,previous.totals.totalKids),compare('noShows','No-show Covers',aggregate.totals.noShowCovers,previous.totals.noShowCovers),compare('noShowRate','No-show Rate',currentNoShowRate,previousNoShowRate),compare('walkIns','Walk-ins',aggregate.totals.walkIns,previous.totals.walkIns),compare('doubleDine','Double Dine Pax',aggregate.totals.doubleDinePax,previous.totals.doubleDinePax),
      ...revenueKeys.map(key=>compare(key,labelKey(key),Number(aggregate.revenue[key]),Number(previous.revenue[key]))),
      compare('upsell','Upsell Revenue',Number(aggregate.upselling.totalRevenue),Number(previous.upselling.totalRevenue)),compare('upsellItems','Items Sold',aggregate.upselling.itemsSold,previous.upselling.itemsSold),compare('occasions','Guest Occasions',occasionCount,previousOccasions),
      ...categoryDefaults.map(([key,label])=>compare(`occasion:${key}`,label,aggregate.occasions.find(row=>row.key===key)?.count||0,previous.occasions.find(row=>row.key===key)?.count||0))
    ]:[]
    if(financeAvailable&&payload&&previousInput){for(const [key,label] of [['mtdFoodCostPercent','Food Cost %'],['mtdBeverageCostPercent','Beverage Cost %'],['foodCostPerCover','Food Cost / Cover'],['beverageCostPerCover','Beverage Cost / Cover']] as const)comparisonMetrics.push(compare(key,label,Number(payload[key]||0),Number(previousInput.financePayload[key]||0)))}
    const financeComplete=Boolean(input&&monthlyFinanceComplete(input.financePayload)),financeVerified=Boolean(input?.financeStatus.startsWith('verified')),opsComplete=approvedDays===expectedDays&&expectedDays>0&&monthEnd<=today,commentary=Boolean(input?.managerCommentary.trim())
    const readiness:MonthlyReportView['readiness']=[{label:'Operational Daily Coverage',state:opsComplete?'complete':current?'pending':approvedDays?'warning':'missing',detail:`${approvedDays} / ${expectedDays} elapsed service nights approved`},{label:'Revenue',state:approvedDays?'complete':'missing',detail:`${approvedDays} approved day${approvedDays===1?'':'s'}`},{label:'Upselling',state:approvedDays?'complete':'missing',detail:aggregate.upselling.totalRevenue},{label:'Guest Experience',state:approvedDays?'complete':'missing',detail:`${occasionCount} occasions`},{label:'People / Training',state:'complete',detail:`${staffing.currentTeamSize} current team · ${operational.training.sessions} trainings`},{label:'Maintenance',state:'complete',detail:`${operational.maintenance.unresolved} unresolved`},{label:'Finance Inputs',state:financeComplete?'complete':input?'warning':'missing',detail:financeComplete?'Required fields complete':'Required month-end values pending'},{label:'Finance Verification',state:financeVerified?'complete':'pending',detail:financeVerified?input!.financeStatus.replaceAll('_',' '):'Manager verification pending'},{label:'Manager Commentary',state:commentary?'complete':'missing',detail:commentary?'Saved':'Required for readiness'}]
    const overallStatus:MonthlyReportView['overallStatus']=opsComplete&&financeComplete&&financeVerified&&commentary?'MONTHLY REPORT READY':!financeComplete||!financeVerified?'FINANCE PENDING':opsComplete?'OPERATIONS COMPLETE':'MONTH IN PROGRESS'
    return{outlet:{id:outlet.id,key:outlet.scopeKey,name:outlet.displayName},monthStart,monthEnd,today,authority:{state,label,approvedDays,expectedDays,totalDays:dates.length},days,...aggregate,attention:{noShowRate:aggregate.totals.totalCovers?round2(aggregate.totals.noShowCovers/aggregate.totals.totalCovers*100):null,highestCoversDay:highest(),lowestCoversDay:highest(true),busiestServiceDay:busiest},staffing,training:{sessions:operational.training.sessions,participants:operational.training.participants,attendance:operational.training.participants?operational.training.attended:null,hours:null},maintenance:{opened:operational.maintenance.issuesReported,completed:operational.maintenance.completedDuringPeriod,stillOpen:operational.maintenance.open,inProgress:operational.maintenance.inProgress,unresolved:operational.maintenance.unresolved,items:(operational.maintenance.records||[]).filter(item=>!String(item.status).toLowerCase().includes('complete')).slice(0,4).map(item=>({id:item.id,issue:item.issue,status:item.status,area:item.area}))},finance:{input,complete:financeComplete,foodMatched:payload?matched(payload.enteredFoodCostPercent,payload.calculatedFoodCostPercent):null,beverageMatched:payload?matched(payload.enteredBeverageCostPercent,payload.calculatedBeverageCostPercent):null},comparison:{available:comparisonAvailable,reason:comparisonAvailable?'Authoritative approved Daily data is available for both months.':'Previous Month Comparison unavailable — approved Daily authority is required for both months.',previousMonthStart,previousMonthEnd,financeAvailable,metrics:comparisonMetrics},readiness,overallStatus,legacyCommentary:await this.reporting.getManagerSummary('month',monthStart,monthEnd)}
  }
  async save(month:string,input:{expectedRevision:number|null;financePayload:unknown;managerCommentary?:string;followUpsChanges?:string},outlet:{id:string;scopeKey:string;displayName:string},principal:AuthPrincipal){if(!validMonth(month))throw new Error('MONTHLY_REPORT_MONTH_INVALID');await this.inputs.save({outletScopeId:outlet.id,monthStart:`${month}-01`,...input},principal);return this.view(month,outlet)}
  async verify(month:string,expectedRevision:number,outlet:{id:string;scopeKey:string;displayName:string},principal:AuthPrincipal){if(!validMonth(month))throw new Error('MONTHLY_REPORT_MONTH_INVALID');await this.inputs.verify(outlet.id,`${month}-01`,expectedRevision,principal);return this.view(month,outlet)}
}
