import type { PGlite } from '@electric-sql/pglite'
import type { WeeklyReportDay, WeeklyReportView } from '../src/domain.js'
import { addCalendarDays, calendarDates, serviceDate, weekRange } from '../src/service-date.js'
import { DailyReportSnapshotRepository, type DailyReportFrozenPayload } from './daily-report-snapshot-repository.js'
import { ReportingRepository } from './reporting-repository.js'

const cents = (value: unknown) => Math.round(Number(value || 0) * 100)
const amount = (value: number) => (value / 100).toFixed(2)
const round2 = (value: number) => Number(value.toFixed(2))
const categoryDefaults = [['honeymoon','Honeymoon'],['birthday','Birthday'],['anniversary','Anniversary'],['seeYouSoon','See You Soon'],['vip','VIP'],['tlc','TLC'],['siyamFamily','Repeaters / Siyam Family'],['famtrip','Famtrip'],['presstrip','Presstrip']] as const
const revenueKeys = ['foodRevenue','beverageRevenue','wineRevenue','liquorRevenue','totalSale','totalDiscount','totalVoid','netSale','totalRevenue'] as const

export class WeeklyReportService {
  private readonly snapshots: DailyReportSnapshotRepository
  constructor(private readonly db: PGlite, private readonly reporting: ReportingRepository, private readonly todayProvider = serviceDate) { this.snapshots = new DailyReportSnapshotRepository(db) }

  private aggregate(snapshots: Array<{ serviceDate: string; frozenPayload: DailyReportFrozenPayload }>) {
    const totals = { totalCovers:0,totalBookings:0,totalKids:0,arrivedCovers:0,noShowCovers:0,walkIns:0,doubleDinePax:0,averageCoversPerServiceNight:0 }
    const revenueCents: Record<string,number> = { foodRevenue:0,beverageRevenue:0,wineRevenue:0,liquorRevenue:0,totalSale:0,totalDiscount:0,totalVoid:0,netSale:0,totalRevenue:0 }
    const itemMap=new Map<string,{quantity:number;revenue:number}>(), sellerMap=new Map<string,number>(); let chargeable=0,wineSpirits=0,itemsSold=0
    const occasionMap=new Map<string,{key:string;label:string;count:number;covers:number}>(categoryDefaults.map(([key,label])=>[key,{key,label,count:0,covers:0}]))
    const variances: WeeklyReportView['variances'] = []
    for(const snapshot of snapshots){const c=snapshot.frozenPayload;totals.totalCovers+=c.servicePerformance.totalCovers;totals.totalBookings+=c.servicePerformance.totalBookings;totals.totalKids+=c.servicePerformance.kids;totals.arrivedCovers+=c.servicePerformance.arrivedCovers;totals.noShowCovers+=c.servicePerformance.noShowCovers;totals.walkIns+=c.servicePerformance.walkIns;totals.doubleDinePax+=Number(c.serviceVerification.doubleDinePax||0)
      for(const key of revenueKeys) revenueCents[key]+=cents(c.symphony[key])
      for(const detail of c.upselling.details||[]){const row=detail as Record<string,unknown>;const itemName=String(row.item||'Unspecified');const seller=String(row.soldBy||'');const rowCents=cents(row.amount);itemsSold+=Number(row.quantity||0);if(row.source==='Wine / Spirits')wineSpirits+=rowCents;else chargeable+=rowCents;const item=itemMap.get(itemName)||{quantity:0,revenue:0};item.quantity+=Number(row.quantity||0);item.revenue+=rowCents;itemMap.set(itemName,item);if(seller&&seller!=='Unassigned')sellerMap.set(seller,(sellerMap.get(seller)||0)+rowCents)}
      for(const categoryValue of c.guestOccasions.categories){const category=categoryValue as Record<string,unknown>;const current=occasionMap.get(String(category.key))||{key:String(category.key),label:String(category.label),count:0,covers:0};current.count+=Number(category.count||0);current.covers+=Number(category.covers||0);occasionMap.set(current.key,current)}
      const verification=c.revenueVerification;if(verification?.acknowledged&&verification.netSale&&verification.totalRevenue&&verification.difference)variances.push({date:snapshot.serviceDate,netSale:verification.netSale,totalRevenue:verification.totalRevenue,difference:verification.difference,verifiedBy:verification.verifiedByName||'Authenticated manager',verifiedAt:verification.verifiedAt||''})
    }
    totals.averageCoversPerServiceNight=snapshots.length?round2(totals.totalCovers/snapshots.length):0
    const topItems=[...itemMap].map(([label,value])=>({label,quantity:value.quantity,revenue:amount(value.revenue)})).sort((a,b)=>b.quantity-a.quantity||Number(b.revenue)-Number(a.revenue)||a.label.localeCompare(b.label))
    const topSellers=[...sellerMap].map(([label,revenue])=>({label,revenue:amount(revenue)})).sort((a,b)=>Number(b.revenue)-Number(a.revenue)||a.label.localeCompare(b.label))
    return {totals,revenue:Object.fromEntries(Object.entries(revenueCents).map(([key,value])=>[key,amount(value)])) as WeeklyReportView['revenue'],variances,upselling:{totalRevenue:amount(chargeable+wineSpirits),itemsSold,chargeableRevenue:amount(chargeable),wineSpiritsRevenue:amount(wineSpirits),topItem:topItems[0]?.label||'—',topSeller:topSellers[0]?.label||'—',topItems:topItems.slice(0,3),topSellers:topSellers.slice(0,3)},occasions:[...occasionMap.values()]}
  }

  async view(containingDate:string,outlet:{id:string;scopeKey:string;displayName:string}):Promise<WeeklyReportView>{const [weekStart,weekEnd]=weekRange(containingDate),today=this.todayProvider();const dates=calendarDates(weekStart,weekEnd);const snapshots=await this.snapshots.currentApprovedSnapshots(outlet.id,weekStart,weekEnd);const byDate=new Map(snapshots.map(item=>[item.serviceDate,item]));const currentRows=(await this.db.query<any>("select id,service_date::text,status from daily_reports where outlet_scope_id=$1 and service_date between $2 and $3 and is_current_authority=true",[outlet.id,weekStart,weekEnd])).rows;const reports=new Map(currentRows.map((row:any)=>[row.service_date,row]));
    const days:WeeklyReportDay[]=dates.map(date=>{const snapshot=byDate.get(date);if(snapshot){const c=snapshot.frozenPayload;return{date,status:'approved',reportId:snapshot.dailyReportId,covers:c.servicePerformance.totalCovers,bookings:c.servicePerformance.totalBookings,kids:c.servicePerformance.kids,arrivedCovers:c.servicePerformance.arrivedCovers,noShowCovers:c.servicePerformance.noShowCovers,walkIns:c.servicePerformance.walkIns,doubleDinePax:Number(c.serviceVerification.doubleDinePax||0)}}const report=reports.get(date);const status:WeeklyReportDay['status']=report?.status==='draft'?'draft':report?.status==='reviewed'?'reviewed':date>today?'not-yet-closed':date===today?'in-progress':'missing-report';return{date,status,reportId:report?.id||null,covers:null,bookings:null,kids:null,arrivedCovers:null,noShowCovers:null,walkIns:null,doubleDinePax:null}})
    const aggregate=this.aggregate(snapshots);const approvedDays=snapshots.length;const expectedDays=weekStart>today?0:weekEnd<today?7:dates.filter(date=>date<=today).length;const currentWeek=weekStart<=today&&weekEnd>=today;const state=approvedDays===7?'complete':currentWeek?'in-progress':approvedDays===0?'no-approved-data':'partial';const label=state==='complete'?'WEEK COMPLETE':state==='in-progress'?'WEEK IN PROGRESS':state==='partial'?'PARTIAL WEEK':'NO APPROVED DATA'
    const approvedDaysData=days.filter(day=>day.status==='approved');const highest=(field:'covers'|'noShowCovers'|'bookings')=>[...approvedDaysData].sort((a,b)=>Number(b[field])-Number(a[field])||a.date.localeCompare(b.date))[0]?.date||null
    const attention={noShowCovers:aggregate.totals.noShowCovers,noShowRate:aggregate.totals.totalCovers?round2(aggregate.totals.noShowCovers/aggregate.totals.totalCovers*100):null,walkIns:aggregate.totals.walkIns,doubleDinePax:aggregate.totals.doubleDinePax,highestNoShowDay:highest('noShowCovers'),highestCoversDay:highest('covers'),busiestServiceDay:highest('bookings')}
    const previousWeekStart=addCalendarDays(weekStart,-7),previousWeekEnd=addCalendarDays(weekEnd,-7),previousSnapshots=await this.snapshots.currentApprovedSnapshots(outlet.id,previousWeekStart,previousWeekEnd);const previous=this.aggregate(previousSnapshots);const occasionCount=aggregate.occasions.reduce((sum,row)=>sum+row.count,0),previousOccasions=previous.occasions.reduce((sum,row)=>sum+row.count,0);const compare=(key:string,label:string,current:number,prior:number)=>({key,label,current,previous:prior,difference:round2(current-prior),changePercent:prior?round2((current-prior)/Math.abs(prior)*100):current?null:0});const comparisonAvailable=approvedDays===7&&previousSnapshots.length===7;const comparison={available:comparisonAvailable,reason:comparisonAvailable?'Approved Daily authority is complete for both weeks.':'Previous Week Comparison Unavailable — both weeks require 7 approved Daily snapshots.',previousWeekStart,previousWeekEnd,metrics:comparisonAvailable?[compare('covers','Covers',aggregate.totals.totalCovers,previous.totals.totalCovers),compare('bookings','Bookings',aggregate.totals.totalBookings,previous.totals.totalBookings),compare('noShows','No-show Covers',aggregate.totals.noShowCovers,previous.totals.noShowCovers),compare('revenue','Total Revenue',Number(aggregate.revenue.totalRevenue),Number(previous.revenue.totalRevenue)),compare('upsell','Upsell Revenue',Number(aggregate.upselling.totalRevenue),Number(previous.upselling.totalRevenue)),compare('occasions','Guest Occasions',occasionCount,previousOccasions)]:[]}
    const commentary=await this.reporting.getManagerSummary('week',weekStart,weekEnd);const completeness=approvedDays===7?'complete':approvedDays?'partial':'missing';const status=[{label:'Approved Daily Reports',state:completeness,detail:`${approvedDays} / 7`},{label:'Operational Aggregation',state:completeness,detail:label},{label:'Revenue',state:completeness,detail:`${approvedDays} approved day${approvedDays===1?'':'s'}`},{label:'Guest Experience',state:completeness,detail:`${occasionCount} occasion${occasionCount===1?'':'s'}`},{label:'Upselling',state:completeness,detail:aggregate.upselling.totalRevenue},{label:'Manager Commentary',state:commentary?'saved':'missing',detail:commentary?'Saved':'Optional'}] as WeeklyReportView['status']
    return{outlet:{id:outlet.id,key:outlet.scopeKey,name:outlet.displayName},weekStart,weekEnd,today,authority:{state,label,approvedDays,expectedDays,totalDays:7},days,...aggregate,attention,comparison,commentary,status}
  }
  async saveCommentary(weekStart:string,managerNotes:string,outlet:{id:string;scopeKey:string;displayName:string},actor:string){const [start,end]=weekRange(weekStart);if(start!==weekStart)throw new Error('Weekly commentary must use the Monday week start.');await this.reporting.saveManagerSummary({periodType:'week',startDate:start,endDate:end,managerNotes:String(managerNotes||'').trim().slice(0,10000)},actor);return this.view(start,outlet)}
}
