alter table bookings add column if not exists reservation_date date;
alter table bookings add column if not exists import_source text;
alter table bookings add column if not exists created_by text;
alter table bookings add column if not exists updated_by text;
alter table bookings add column if not exists venue_key text not null default 'andalucia';
alter table bookings add column if not exists source_activity_label text;
alter table bookings add column if not exists source_booking_key text;
alter table bookings add column if not exists parse_confidence numeric(5,4);
alter table bookings add column if not exists review_required boolean not null default false;
alter table bookings add column if not exists raw_import_payload jsonb;
alter table bookings add column if not exists source_booking_status text;
alter table bookings add column if not exists source_filename text;
alter table bookings add column if not exists source_report_date date;
alter table bookings add column if not exists source_parser_version text;
alter table bookings add column if not exists source_guest_notes text;
alter table training_sessions add column if not exists end_time time;
alter table training_sessions add column if not exists location text not null default 'Andalucía';
alter table training_sessions add column if not exists source text not null default 'manual';
alter table training_sessions add column if not exists source_file_name text;
alter table training_sessions add column if not exists import_batch_id uuid references training_import_batches(id);
alter table training_sessions add column if not exists imported_at timestamptz;
alter table training_sessions add column if not exists source_data jsonb;
alter table training_sessions add column if not exists manager_corrected boolean not null default false;
alter table training_import_batches add column if not exists active boolean not null default true;
alter table training_import_batches add column if not exists removed_at timestamptz;
alter table training_import_batches add column if not exists removed_by text;
alter table training_import_batches add column if not exists removal_action text;
alter table training_import_batches add column if not exists replacement_batch_id uuid;
alter table chargeable_item_records add column if not exists charge_date date;
alter table chargeable_item_records add column if not exists guest_name text;
alter table chargeable_item_records add column if not exists room_number text;
alter table chargeable_item_records add column if not exists table_number text;
alter table chargeable_item_records add column if not exists item_label text;
alter table chargeable_item_records add column if not exists item_category text;
alter table chargeable_item_records add column if not exists quantity integer not null default 1;
alter table chargeable_item_records add column if not exists unit_price numeric(10,2);
alter table chargeable_item_records add column if not exists total_amount numeric(10,2);
alter table chargeable_item_records add column if not exists notes text not null default '';
alter table chargeable_item_records add column if not exists active boolean not null default true;
alter table chargeable_item_records add column if not exists created_by text;
alter table chargeable_item_records add column if not exists updated_by text;
alter table guest_occasions add column if not exists status_value text;
alter table guest_occasions add column if not exists source text not null default 'manual';
alter table guest_occasions add column if not exists source_text text not null default '';
alter table guest_occasions add column if not exists manual_guest_name text;
alter table guest_occasions add column if not exists manual_room_number text;
alter table guest_occasions add column if not exists occasion_date date;
alter table guest_occasions add column if not exists occasion_time time;
alter table guest_occasions add column if not exists manual_table_number text;
alter table guest_occasions add column if not exists manual_waiter_id uuid references staff(id);
alter table guest_occasions add column if not exists active boolean not null default true;
alter table guest_occasions add column if not exists created_by text;
alter table guest_occasions add column if not exists updated_by text;
alter table maintenance_issues add column if not exists issue_date date;
alter table maintenance_issues add column if not exists area_value text;
alter table maintenance_issues add column if not exists reported_by_staff_id uuid references staff(id);
alter table maintenance_issues add column if not exists notes text not null default '';
alter table maintenance_issues add column if not exists created_by text;
alter table maintenance_issues add column if not exists updated_by text;
