alter table bookings alter column reservation_date set not null;
alter table chargeable_item_records alter column charge_date set not null;
alter table chargeable_item_records alter column guest_name set not null;
alter table chargeable_item_records alter column item_label set not null;
alter table chargeable_item_records alter column item_category set not null;
alter table chargeable_item_records alter column unit_price set not null;
alter table chargeable_item_records alter column total_amount set not null;
alter table guest_occasions alter column status_value set not null;
alter table guest_occasions alter column manual_guest_name set not null;
alter table guest_occasions alter column occasion_date set not null;
alter table guest_occasions alter column occasion_time set not null;
alter table maintenance_issues alter column issue_date set not null;
alter table maintenance_issues alter column area_value set not null;
alter table training_import_batches drop constraint if exists training_import_batches_file_hash_key;
create unique index if not exists training_import_batches_active_file_hash_unique on training_import_batches(file_hash) where active=true;
create index if not exists training_import_natural_key_idx on training_sessions(training_date,lower(title),training_time,coalesce(end_time,training_time));
create index if not exists booking_reservation_date_idx on bookings(reservation_date);
create index if not exists booking_waiter_idx on bookings(waiter_id);
create unique index if not exists booking_import_source_key_unique on bookings(source_booking_key) where source_booking_key is not null;
create index if not exists chargeable_date_idx on chargeable_item_records(charge_date,active);
create index if not exists chargeable_booking_idx on chargeable_item_records(booking_id);
create index if not exists chargeable_waiter_idx on chargeable_item_records(waiter_id);
create index if not exists guest_occasion_date_idx on guest_occasions(occasion_date,active);
create index if not exists guest_occasion_booking_idx on guest_occasions(booking_id);
create unique index if not exists guest_occasion_booking_type_unique on guest_occasions(booking_id,occasion_type) where booking_id is not null;
create index if not exists maintenance_issue_date_idx on maintenance_issues(issue_date);
create index if not exists maintenance_issue_status_idx on maintenance_issues(status);
create index if not exists maintenance_issue_reporter_idx on maintenance_issues(reported_by_staff_id);
