import { useEffect, useState } from 'react'
import { databaseAdminApi } from './api'
import type { DatabaseAdminHealth, DatabaseBackupInventoryItem } from './domain'
import './database-health.css'

const formatDateTime = (value?: string | null) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Indian/Maldives' }).format(new Date(value)) : 'Pending'
const formatBytes = (value: number) => value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(1)} GB` : `${(value / 1024 ** 2).toFixed(1)} MB`
const categoryLabel = (value: string) => value.replace(/^automatic-/, '').replaceAll('-', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const restoreLabel = (value: string) => value.replace('RESTORE_TEST_', '').replaceAll('_', ' ')

export function DatabaseHealthPanel() {
  const [health, setHealth] = useState<DatabaseAdminHealth | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(''); const [selected, setSelected] = useState<DatabaseBackupInventoryItem | null>(null)
  const load = async () => { setError(''); try { setHealth(await databaseAdminApi.health()) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Database health is unavailable.') } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (selected) void databaseAdminApi.inspect(selected.backupId).catch(() => undefined) }, [selected])
  const act = async (key: string, action: () => Promise<unknown>, message: string) => { setBusy(key); setError(''); setNotice(''); try { await action(); setNotice(message); await load() } catch (actionError) { setError(actionError instanceof Error ? actionError.message : 'The database administration action failed.') } finally { setBusy('') } }
  if (!health && !error) return <section className="panel database-health-state" role="status">Loading protected database health…</section>
  if (!health) return <section className="panel database-health-state error-state"><p>{error}</p><button className="secondary" onClick={() => void load()}>Try Again</button></section>
  const databaseHealthy = health.database.status === 'HEALTHY' || health.database.status === 'BACKUP_RECOMMENDED'
  const recovery = health.recovery; const incident = recovery.activeIncident
  const prepareRecovery = () => { if (!incident?.selectedBackupId) return; const rollback = recovery.candidates.find(item => item.backupId !== incident.selectedBackupId)?.backupId || incident.selectedBackupId; if (!window.confirm('Prepare a single-use recovery authorization for this verified recovery point? The live application must be stopped before any offline promotion. The failed store will be quarantined and the rollback source preserved.')) return; void act('recovery-authorize', () => databaseAdminApi.prepareRecoveryAuthorization(incident.id, rollback), 'Recovery authorization prepared. Promotion remains an offline Owner action.') }
  return <section className="database-health-admin">
    <header className="database-health-heading"><div><p className="eyebrow">OWNER PLATFORM ADMINISTRATION</p><h2>Database Health</h2><p>Verified recovery points and restore readiness for the Andalucía operational store.</p></div><button className="primary" disabled={Boolean(busy) || Boolean(health.pendingBackupRequest)} onClick={() => void act('request', databaseAdminApi.requestBackup, 'Verified backup requested. It will run during the next controlled offline backup window.')}>{busy === 'request' ? 'Requesting…' : health.pendingBackupRequest ? 'Backup Requested' : 'Request Verified Backup'}</button></header>
    {error && <p className="database-health-message error-state" role="alert">{error}</p>}{notice && <p className="database-health-message" role="status">{notice}</p>}
    <div className="database-health-cards">
      <article><span>Database Status</span><strong className={databaseHealthy ? 'good' : 'attention'}>{health.database.status.replaceAll('_', ' ')}</strong></article>
      <article><span>Canonical Store</span><strong>{health.database.storeRole === 'canonical' ? 'Verified' : 'Attention Required'}</strong></article>
      <article><span>Schema Version</span><strong>{health.database.migrationVersion}</strong></article>
      <article><span>Last Verified Backup</span><strong>{formatDateTime(health.lastVerifiedBackup?.createdAt)}</strong><small>{health.lastVerifiedBackup ? categoryLabel(health.lastVerifiedBackup.category) : 'No verified backup'}</small></article>
      <article><span>Last Restore Test</span><strong>{health.lastRestoreTest ? restoreLabel(health.lastRestoreTest.restoreTestStatus) : 'Pending'}</strong><small>{formatDateTime(health.lastRestoreTest?.latestRestoreTestAt)}</small></article>
      <article><span>Recovery Readiness</span><strong className={health.recoveryReadiness === 'READY' ? 'good' : 'attention'}>{health.recoveryReadiness === 'READY' ? 'Ready' : 'Attention Required'}</strong></article>
    </div>
    {incident && <section className="panel recovery-incident" aria-labelledby="recovery-incident-title"><header><div><p className="eyebrow">CONTROLLED DISASTER RECOVERY</p><h3 id="recovery-incident-title">Database recovery required</h3></div><span className="backup-state invalid">{incident.state.replaceAll('_', ' ')}</span></header><p>The operational database failed health checks. Automatic repair is blocked. Select a verified recovery point and rehearse it before preparing promotion authority.</p><div className="recovery-candidates">{recovery.candidates.map(candidate => <button key={candidate.backupId} className={incident.selectedBackupId === candidate.backupId ? 'selected' : ''} disabled={Boolean(busy)} onClick={() => void act(`candidate-${candidate.backupId}`, () => databaseAdminApi.selectRecoveryCandidate(incident.id, candidate.backupId), 'Recovery candidate selected.')}><b>{formatDateTime(candidate.createdAt)}</b><span>{categoryLabel(candidate.category)} · Schema {candidate.schemaVersion}</span><small>{candidate.verificationStatus} · {restoreLabel(candidate.restoreTestStatus)} · {candidate.protected ? 'Protected' : 'Unpinned'}</small></button>)}</div>{incident.gapAnalysis.some(gap => gap.material) && <aside className="database-health-warnings"><b>Known operational differences</b><ul>{incident.gapAnalysis.filter(gap => gap.material).map(gap => <li key={gap.area}>{gap.area}: candidate differs from latest known healthy state</li>)}</ul></aside>}<div className="backup-actions"><button className="secondary" disabled={!incident.selectedBackupId || Boolean(busy)} onClick={() => void act('recovery-rehearse', () => databaseAdminApi.rehearseRecovery(incident.id), 'Fresh recovery rehearsal passed.')}>Rehearse Selected Recovery</button><button className="primary" disabled={incident.state !== 'REHEARSAL_PASSED' || Boolean(busy)} onClick={prepareRecovery}>Prepare Owner Authorization</button></div></section>}
    {health.warnings.length > 0 && <aside className="database-health-warnings"><b>Health notes</b><ul>{health.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul></aside>}
    <section className="panel backup-history"><header><div><p className="eyebrow">RECOVERY POINTS</p><h3>Backup History</h3></div><div className="backup-storage"><b>{formatBytes(health.storage.totalBackupStorageBytes)}</b><span>{health.storage.verifiedBackupCount} verified backups</span></div></header>
      <div className="backup-table-wrap"><table><thead><tr><th>Date / time</th><th>Category</th><th>Schema</th><th>Verification</th><th>Restore test</th><th>Size</th><th>Protected</th><th>Actions</th></tr></thead><tbody>{health.inventory.map(item => <tr key={item.backupId}><td>{formatDateTime(item.createdAt)}</td><td>{categoryLabel(item.category)}</td><td>{item.schemaVersion}</td><td><span className={`backup-state ${item.verificationStatus.toLowerCase()}`}>{item.verificationStatus}</span></td><td>{restoreLabel(item.restoreTestStatus)}{item.latestRestoreTestAt && <small>{formatDateTime(item.latestRestoreTestAt)}</small>}</td><td>{formatBytes(item.sizeBytes)}</td><td>{item.protected ? <span title={item.protectionReasons.join('; ')}>Yes</span> : 'No'}</td><td><div className="backup-actions"><button className="secondary" onClick={() => setSelected(item)}>Details</button><button className="secondary" disabled={Boolean(busy) || item.verificationStatus !== 'VERIFIED'} onClick={() => void act(`restore-${item.backupId}`, () => databaseAdminApi.rehearse(item.backupId), 'Restore rehearsal passed and evidence was retained.')}>{busy === `restore-${item.backupId}` ? 'Testing…' : 'Test Restore'}</button>{!item.protected && <button className="secondary" disabled={Boolean(busy)} onClick={() => void act(`pin-${item.backupId}`, () => databaseAdminApi.pin(item.backupId, true), 'Backup protected.')}>Protect</button>}</div></td></tr>)}</tbody></table></div>
      <div className="backup-mobile-list">{health.inventory.map(item => <article key={item.backupId}><header><b>{categoryLabel(item.category)}</b><span className={`backup-state ${item.verificationStatus.toLowerCase()}`}>{item.verificationStatus}</span></header><p>{formatDateTime(item.createdAt)} · Schema {item.schemaVersion} · {formatBytes(item.sizeBytes)}</p><small>Restore: {restoreLabel(item.restoreTestStatus)} · Protected: {item.protected ? 'Yes' : 'No'}</small><button className="secondary" onClick={() => setSelected(item)}>View Details</button></article>)}</div>
    </section>
    <section className="panel recovery-history"><header><div><p className="eyebrow">DISASTER RECOVERY</p><h3>Recovery Incidents</h3></div></header>{recovery.history.length ? <div className="recovery-history-scroll"><table><thead><tr><th>Date</th><th>Incident</th><th>Condition</th><th>Selected backup</th><th>Rehearsal</th><th>Promotion</th><th>Rollback</th><th>Accepted by</th></tr></thead><tbody>{recovery.history.map(item => <tr key={item.id}><td>{formatDateTime(item.detectedAt)}</td><td>{item.id}</td><td>{item.failureClass.replaceAll('_', ' ')}</td><td>{item.selectedBackupId || '—'}</td><td>{item.rehearsalStatus || '—'}</td><td>{item.promotionStatus || '—'}</td><td>{item.rollbackStatus || '—'}</td><td>{item.acceptedBy || '—'}</td></tr>)}</tbody></table></div> : <p className="recovery-empty">No recovery incidents.</p>}</section>
    <footer className="database-policy-note">Daily: retain {health.policy.retention.daily} verified generations · Weekly: retain {health.policy.retention.weekly} · Restore rehearsal every {health.policy.restoreRehearsalIntervalDays} days. Backup execution requires a controlled offline window.</footer>
    {selected && <div className="modal-backdrop"><section className="modal backup-detail" role="dialog" aria-modal="true" aria-labelledby="backup-detail-title"><button className="close" aria-label="Close backup details" onClick={() => setSelected(null)}>×</button><p className="eyebrow">VERIFIED RECOVERY POINT</p><h2 id="backup-detail-title">{categoryLabel(selected.category)}</h2><dl><div><dt>Created</dt><dd>{formatDateTime(selected.createdAt)}</dd></div><div><dt>Schema</dt><dd>{selected.schemaVersion}</dd></div><div><dt>Verification</dt><dd>{selected.verificationStatus}</dd></div><div><dt>Restore test</dt><dd>{restoreLabel(selected.restoreTestStatus)}</dd></div><div><dt>Size</dt><dd>{formatBytes(selected.sizeBytes)}</dd></div><div><dt>Protected</dt><dd>{selected.protected ? 'Yes' : 'No'}</dd></div></dl>{selected.protectionReasons.length > 0 && <p><b>Protection:</b> {selected.protectionReasons.join('; ')}</p>}<button className="secondary" onClick={() => setSelected(null)}>Close</button></section></div>}
  </section>
}
