import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { maintenanceApi } from './api'
import type { ConfigOption, MaintenanceDuplicateWarning, MaintenanceRecord, MaintenanceSummary, Staff } from './domain'
import './maintenance.css'
import './maintenance-r2-1.css'
import './maintenance-modal.css'
import { serviceDate } from './service-date'
import { consumeWorkflow } from './workflow-intent'
import { defaultMaintenanceReporterId, isActiveAndaluciaStaff } from './maintenance-reporter'

export interface MaintenanceConfiguration { areas: ConfigOption[]; statuses: ConfigOption[] }
const emptySummary: MaintenanceSummary = { openIssues: 0, inProgress: 0, completedToday: 0, unresolved: 0, urgentUnresolved: 0, normalUnresolved: 0 }
const formatDate = (value: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`))
const optionLabel = (options: ConfigOption[], value: string) => options.find(option => option.value === value)?.label || value || '—'
const priorityLabel = (value?: string) => value === 'urgent' ? 'Urgent' : 'Normal'
export function MaintenancePage({ staff, authenticatedStaffId, configuration, onToast }: { staff: Staff[]; authenticatedStaffId: string | null; configuration: MaintenanceConfiguration; onToast: (message: string) => void }) {
  const [records, setRecords] = useState<MaintenanceRecord[]>([]); const [summary, setSummary] = useState<MaintenanceSummary>(emptySummary)
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('active'); const [dateFilter, setDateFilter] = useState('')
  const [editing, setEditing] = useState<MaintenanceRecord | 'new' | null>(null); const [viewing, setViewing] = useState<MaintenanceRecord | null>(null)
  useEffect(() => { if (consumeWorkflow('maintenance-add')) setEditing('new') }, [])
  const load = async () => { setLoading(true); setError(''); try { const [nextRecords, nextSummary] = await Promise.all([maintenanceApi.list(), maintenanceApi.summary(serviceDate())]); setRecords(nextRecords); setSummary(nextSummary) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load maintenance issues.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const stage = (record: MaintenanceRecord) => configuration.statuses.find(option => option.value === record.status)?.metadata?.maintenanceStage || 'open'
  const visible = useMemo(() => records.filter(record => { const matchesStatus = statusFilter === 'all' || (statusFilter === 'active' ? stage(record) !== 'completed' : record.status === statusFilter); const reporter = record.reportedBy ? `${record.reportedBy.name} ${record.reportedBy.number}` : `${record.reporterNameSnapshot || ''} ${record.reporterNumberSnapshot || ''}`; return matchesStatus && (!dateFilter || record.dateReported === dateFilter) && `${record.issue} ${record.notes} ${record.referenceFollowUp} ${record.area} ${reporter}`.toLowerCase().includes(query.toLowerCase()) }), [records, query, statusFilter, dateFilter, configuration.statuses])
  const save = async (record: MaintenanceRecord) => { const saved = records.some(item => item.id === record.id) ? await maintenanceApi.update(record) : await maintenanceApi.create(record); setRecords(current => current.some(item => item.id === saved.id) ? current.map(item => item.id === saved.id ? saved : item) : [saved, ...current]); setSummary(await maintenanceApi.summary(serviceDate())); return saved }
  const quickStatus = async (record: MaintenanceRecord, status: string) => { try { const saved = await save({ ...record, status }); onToast('Maintenance status updated.'); if (viewing?.id === saved.id) setViewing(saved) } catch (saveError) { onToast(saveError instanceof Error ? saveError.message : 'Unable to update maintenance status.') } }
  const reporterText = (record: MaintenanceRecord) => record.reportedBy ? `${record.reportedBy.name} · ${record.reportedBy.number}` : record.reporterNameSnapshot ? `${record.reporterNameSnapshot}${record.reporterNumberSnapshot ? ` · ${record.reporterNumberSnapshot}` : ''}` : 'Not recorded'
  return <>
    <section className="maintenance-toolbar"><div><p className="eyebrow">RESTAURANT MAINTENANCE</p><h2>Operational issue tracker</h2></div><button className="primary" onClick={() => setEditing('new')}>＋ Add Maintenance Issue</button></section>
    <section className="maintenance-summary"><article className="panel open"><span>Open Issues</span><strong>{summary.openIssues}</strong></article><article className="panel progress"><span>In Progress</span><strong>{summary.inProgress}</strong></article><article className="panel urgent"><span>Urgent Attention</span><strong>{summary.urgentUnresolved}</strong></article><article className="panel complete"><span>Completed Today</span><strong>{summary.completedToday}</strong></article></section>
    <section className="panel maintenance-panel"><div className="maintenance-filters"><input aria-label="Search maintenance issues" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search issue, area, follow-up or reporter"/><select aria-label="Filter maintenance status" value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="active">Active / unresolved</option><option value="all">All statuses</option>{configuration.statuses.map(option => <option key={option.id} value={option.value}>{option.label}</option>)}</select><label>Date reported<input aria-label="Filter maintenance date" type="date" value={dateFilter} onChange={event => setDateFilter(event.target.value)}/></label>{dateFilter && <button className="link" onClick={() => setDateFilter('')}>Clear date</button>}</div>
    {loading && <div className="inline-state">Loading maintenance issues…</div>}{error && <div className="inline-state error-state"><p>{error}</p><button className="secondary" onClick={() => void load()}>Try again</button></div>}{!loading && !error && <>
      <div className="maintenance-table-wrap" tabIndex={0} aria-label="Maintenance issues table"><table className="maintenance-table"><thead><tr><th>Issue</th><th>Date</th><th>Area</th><th>Priority</th><th>Reported By</th><th>Status</th><th>Reference / Follow-up</th><th/></tr></thead><tbody>{visible.map(record => { const status = configuration.statuses.find(option => option.value === record.status); const completed = stage(record) === 'completed'; return <tr key={record.id}><td><b>{record.issue}</b><small>{record.notes || 'No notes'}</small></td><td>{formatDate(record.dateReported)}</td><td>{optionLabel(configuration.areas, record.area)}</td><td><span className={`maintenance-priority ${record.priority === 'urgent' ? 'urgent' : ''}`}>{priorityLabel(record.priority)}</span></td><td>{reporterText(record)}</td><td>{completed ? <span className="maintenance-status" style={{ borderColor: status?.color }}>{status?.label || record.status}</span> : <select aria-label={`Status for ${record.issue}`} value={record.status} style={{ borderColor: status?.color }} onChange={event => void quickStatus(record, event.target.value)}>{configuration.statuses.filter(option => option.active && stage({ ...record, status: option.value }) !== 'completed' || option.value === record.status || stage(record) === 'inProgress' && option.metadata?.maintenanceStage === 'completed').map(option => <option key={option.id} value={option.value}>{option.label}</option>)}</select>}</td><td className="maintenance-follow-up">{record.referenceFollowUp || '—'}</td><td className="row-actions"><button className="link" onClick={() => setViewing(record)}>View</button>{!completed && <button className="link" onClick={() => setEditing(record)}>Edit</button>}</td></tr>})}</tbody></table></div>
      <div className="maintenance-cards">{visible.map(record => { const completed = stage(record) === 'completed'; return <article className="maintenance-card" key={record.id}><div className="maintenance-card-head"><h3>{record.issue}</h3><span className={`maintenance-priority ${record.priority === 'urgent' ? 'urgent' : ''}`}>{priorityLabel(record.priority)}</span></div><dl><div><dt>Area</dt><dd>{optionLabel(configuration.areas, record.area)}</dd></div><div><dt>Reported</dt><dd>{formatDate(record.dateReported)}</dd></div><div><dt>Reporter</dt><dd>{reporterText(record)}</dd></div><div><dt>Status</dt><dd>{optionLabel(configuration.statuses, record.status)}</dd></div>{record.referenceFollowUp && <div className="wide"><dt>Reference / Follow-up</dt><dd>{record.referenceFollowUp}</dd></div>}</dl><div className="maintenance-card-actions"><button className="secondary" onClick={() => setViewing(record)}>View</button>{!completed && <button className="secondary" onClick={() => setEditing(record)}>Edit</button>}</div></article>})}</div>
      {visible.length === 0 && <div className="inline-empty"><span>No maintenance issues match these filters.</span><button className="secondary empty-state-action" onClick={() => setEditing('new')}>＋ Add Maintenance Issue</button></div>}
    </>}</section>
    {editing && <MaintenanceForm record={editing === 'new' ? undefined : editing} staff={staff} authenticatedStaffId={authenticatedStaffId} configuration={configuration} onClose={() => setEditing(null)} onViewExisting={id => { setEditing(null); const found = records.find(item => item.id === id); if (found) setViewing(found) }} onSave={async record => { await save(record); setEditing(null); onToast('Maintenance issue saved.') }}/>} 
    {viewing && <MaintenanceDetails record={viewing} configuration={configuration} onClose={() => setViewing(null)}/>} 
  </>
}

function MaintenanceForm({ record, staff, authenticatedStaffId, configuration, onClose, onSave, onViewExisting }: { record?: MaintenanceRecord; staff: Staff[]; authenticatedStaffId: string | null; configuration: MaintenanceConfiguration; onClose: () => void; onSave: (record: MaintenanceRecord) => Promise<void>; onViewExisting: (id: string) => void }) {
  const openStatus = configuration.statuses.find(option => option.metadata?.maintenanceStage === 'open')?.value || 'open'
  const defaultReporterId = defaultMaintenanceReporterId(staff, authenticatedStaffId)
  const [form, setForm] = useState<MaintenanceRecord>(record || { id: crypto.randomUUID(), issue: '', dateReported: serviceDate(), area: configuration.areas.find(option => option.active)?.value || '', priority: 'normal', status: openStatus, referenceFollowUp: '', notes: '', reportedByStaffId: defaultReporterId, reportedBy: null, revision: 1 })
  const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [warnings, setWarnings] = useState<MaintenanceDuplicateWarning[]>([]); const [confirmedDuplicate, setConfirmedDuplicate] = useState(false)
  const availableStaff = staff.filter(person => person.id === form.reportedByStaffId || isActiveAndaluciaStaff(person)); const update = <K extends keyof MaintenanceRecord>(field: K, value: MaintenanceRecord[K]) => { setForm(current => ({ ...current, [field]: value })); setWarnings([]); setConfirmedDuplicate(false) }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.issue.trim() || !form.dateReported || !form.area || !form.status) return setError('Issue, date reported, area and status are required.'); setSaving(true); setError(''); try { if (!record && !confirmedDuplicate) { const nextWarnings = await maintenanceApi.duplicateReview(form); if (nextWarnings.length) { setWarnings(nextWarnings); setSaving(false); return } } await onSave({ ...form, issue: form.issue.trim() }) } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Unable to save maintenance issue.') } finally { setSaving(false) } }
  return <MaintenanceModal title={record ? 'Edit Maintenance Issue' : 'Add Maintenance Issue'} onClose={onClose}><form className="staff-form maintenance-form" onSubmit={event => void submit(event)}><label>Issue / Title<input autoFocus value={form.issue} onChange={event => update('issue', event.target.value)}/></label><div className="maintenance-form-grid"><label>Date Reported<input type="date" value={form.dateReported} onChange={event => update('dateReported', event.target.value)}/></label><label>Location / Area<select value={form.area} onChange={event => update('area', event.target.value)}>{configuration.areas.filter(option => option.active || option.value === form.area).map(option => <option key={option.id} value={option.value}>{option.label}{!option.active ? ' (Archived · historical)' : ''}</option>)}</select></label><label>Priority<select value={form.priority === 'urgent' ? 'urgent' : 'normal'} onChange={event => update('priority', event.target.value)}><option value="normal">Normal</option><option value="urgent">Urgent</option></select></label><label>Status<select value={form.status} onChange={event => update('status', event.target.value)} disabled={!record}>{configuration.statuses.filter(option => option.active).map(option => <option key={option.id} value={option.value}>{option.label}</option>)}</select></label><label>Reported By<select value={form.reportedByStaffId || ''} onChange={event => update('reportedByStaffId', event.target.value || null)}><option value="">Not recorded</option>{availableStaff.map(person => <option key={person.id} value={person.id} disabled={person.employmentStatus !== 'active'}>{person.name} · {person.number}{person.employmentStatus !== 'active' ? ' (Inactive · historical)' : ''}</option>)}</select></label><label>Reference / Follow-up<input value={form.referenceFollowUp} onChange={event => update('referenceFollowUp', event.target.value)} placeholder="e.g. Engineering informed"/></label></div><label>Notes / Description<textarea rows={4} value={form.notes} onChange={event => update('notes', event.target.value)}/></label>
  {warnings.length > 0 && <section className="maintenance-duplicate"><p className="eyebrow">POSSIBLE EXISTING ISSUE</p>{warnings.map(warning => <article key={warning.id}><b>{warning.issue}</b><span>{optionLabel(configuration.areas, warning.area)} · {optionLabel(configuration.statuses, warning.status)} · {formatDate(warning.dateReported)}</span><small>{warning.reporter}{warning.sameReporter ? ' · Same reporter' : ''}</small><button type="button" className="link" onClick={() => onViewExisting(warning.id)}>View existing issue</button></article>)}<button type="button" className="secondary" onClick={() => { setConfirmedDuplicate(true); setWarnings([]) }}>Continue creating new issue</button></section>}
  {error && <p className="save-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save issue'}</button></div></form></MaintenanceModal>
}

function MaintenanceDetails({ record, configuration, onClose }: { record: MaintenanceRecord; configuration: MaintenanceConfiguration; onClose: () => void }) { const reporter = record.reporterNameSnapshot ? `${record.reporterNameSnapshot}${record.reporterNumberSnapshot ? ` · ${record.reporterNumberSnapshot}` : ''}` : record.reportedBy ? `${record.reportedBy.name} · ${record.reportedBy.number}` : 'Not recorded'; return <MaintenanceModal title="Maintenance Issue Details" onClose={onClose}><div className="maintenance-detail"><span>Issue</span><b>{record.issue}</b><span>Date Reported</span><b>{formatDate(record.dateReported)}</b><span>Area</span><b>{optionLabel(configuration.areas, record.area)}</b><span>Priority</span><b>{priorityLabel(record.priority)}</b><span>Status</span><b>{optionLabel(configuration.statuses, record.status)}</b><span>Reported By</span><b>{reporter}</b><span>Reference / Follow-up</span><b>{record.referenceFollowUp || '—'}</b><span>Notes</span><b>{record.notes || '—'}</b>{record.completedAt && <><span>Completion evidence</span><b>{new Date(record.completedAt).toLocaleString()} · {record.completedByNameSnapshot || 'Historical actor unavailable'}</b></>}<span>Revision</span><b>{record.revision}</b><span>Created</span><b>{record.createdAt ? new Date(record.createdAt).toLocaleString() : '—'} · {record.createdBy || '—'}</b><span>Updated</span><b>{record.updatedAt ? new Date(record.updatedAt).toLocaleString() : '—'} · {record.updatedBy || '—'}</b></div></MaintenanceModal> }

export function MaintenanceConfigurationManager({ configuration, onSave }: { configuration: MaintenanceConfiguration; onSave: (group: 'areas' | 'statuses', option: ConfigOption) => Promise<void> }) {
  const [editing, setEditing] = useState<{ group: 'areas' | 'statuses'; option: ConfigOption } | null>(null)
  return <section className="panel maintenance-config"><div className="panel-title"><div><p className="eyebrow">MAINTENANCE CONFIGURATION</p><h3>Areas and workflow</h3></div></div><div className="maintenance-config-grid"><div><div className="maintenance-config-heading"><h4>Maintenance Areas</h4><button className="primary compact" onClick={() => setEditing({ group: 'areas', option: { id: crypto.randomUUID(), value: '', label: '', active: true } })}>Add Area</button></div>{configuration.areas.map(option => <div className="maintenance-config-row" key={option.id}><div><b>{option.label}</b><small>{option.active ? 'Available for new issues' : 'Archived · historical records preserved'}</small></div><span className={option.active ? 'badge blue' : 'badge'}>{option.active ? 'Active' : 'Archived'}</span><button className="link" onClick={() => setEditing({ group: 'areas', option })}>Edit</button><button className="link" onClick={() => void onSave('areas', { ...option, active: !option.active })}>{option.active ? 'Archive' : 'Restore'}</button></div>)}</div><div><div className="maintenance-config-heading"><h4>Maintenance Workflow</h4></div>{configuration.statuses.filter(option => ['open','in_progress','completed'].includes(option.value)).map(option => <div className="maintenance-config-row" key={option.id}><div><b><span className="status-dot" style={{ background: option.color }}/>{option.label}</b><small>Protected workflow</small></div><span className="badge blue">Protected</span><button className="link" onClick={() => setEditing({ group: 'statuses', option })}>Edit color</button></div>)}</div></div>{editing && <MaintenanceConfigForm group={editing.group} option={editing.option} onClose={() => setEditing(null)} onSave={async option => { await onSave(editing.group, option); setEditing(null) }}/>}</section>
}
function MaintenanceConfigForm({ group, option, onClose, onSave }: { group: 'areas' | 'statuses'; option: ConfigOption; onClose: () => void; onSave: (option: ConfigOption) => Promise<void> }) { const [form, setForm] = useState(option); const [error, setError] = useState(''); return <MaintenanceModal title={group === 'areas' ? (option.value ? 'Edit Maintenance Area' : 'Add Maintenance Area') : `Edit ${option.label} color`} onClose={onClose}><form className="staff-form" onSubmit={event => { event.preventDefault(); setError(''); void onSave(form).catch(saveError => setError(saveError instanceof Error ? saveError.message : 'Unable to save configuration.')) }}>{group === 'areas' && <label>Area Name<input autoFocus value={form.label} onChange={event => setForm(current => ({ ...current, label: event.target.value }))}/></label>}{group === 'statuses' && <label>Display Color<input type="color" value={form.color || '#1b6288'} onChange={event => setForm(current => ({ ...current, color: event.target.value }))}/></label>}{error && <p className="save-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save</button></div></form></MaintenanceModal> }
function MaintenanceModal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.currentTarget === event.target) onClose() }}><section className="modal maintenance-modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-title"><h3>{title}</h3><button aria-label="Close" className="icon-button" onClick={onClose}>×</button></div>{children}</section></div> }
