import { Fragment, useEffect, useState, type ReactNode } from 'react'
import { dailyReportingApi, monthlyReportingApi, reportingApi, weeklyReportingApi } from './api'
import type { DailyReportDoubleDineDetail, DailyReportManualPayload, DailyReportView, DailyReportVoidDetail, MonthlyFinanceField, MonthlyFinancePayload, MonthlyReportView, OperationalReport, WeeklyReportView } from './domain'
import './reports.css'
import { addCalendarDays, addCalendarMonths, monthRange, serviceDate, weekRange } from './service-date'
import { bookingTimeWindow } from './booking-time'

const blankManual = (): DailyReportManualPayload => ({ symphony: { foodRevenue: '', beverageRevenue: '', wineRevenue: '', liquorRevenue: '', totalSale: '', totalDiscount: '', totalVoid: '', netSale: '', totalRevenue: '', voidDetails: [] }, serviceVerification: { doubleDinePax: null, details: [] }, manager: { operationSummary: '', keyOperationalIssue: '', guestFeedbackServiceRecovery: '', followUpRequired: '' }, revenueVerification: { acknowledged: false } })
const money = (value: number | string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value || 0))
const formatDate = (value: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`))
const isDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T00:00:00Z`).getTime())
const labelKey = (key: string) => key.replace(/([A-Z])/g, ' $1').replace(/^./, value => value.toUpperCase())
const displayMoney = (value: string) => value === '' ? 'Not entered' : money(value)
const monthlyFinanceFields:MonthlyFinanceField[]=['foodRequisitions','netFoodCost','foodSales','mtdFoodCostPercent','budgetFoodCostPercent','foodCostVariancePercent','foodCostPerCover','beverageRequisitions','netBeverageCost','beverageSales','mtdBeverageCostPercent','budgetBeverageCostPercent','beverageCostVariancePercent','beverageCostPerCover','storesRequisitionsFood','commissaryRequisitions','butchery','totalFoodRequisitions','storesRequisitionsBeverage','foodToBeverage','beverageToFood','transferIn','transferOut','breakages','foodWastage','beverageWastage','beverageSpoilage','enteredFoodCostPercent','calculatedFoodCostPercent','foodCostPercentDifference','enteredBeverageCostPercent','calculatedBeverageCostPercent','beverageCostPercentDifference']
const blankMonthlyFinance=()=>Object.fromEntries(monthlyFinanceFields.map(field=>[field,null])) as MonthlyFinancePayload

export function ReportsPage({ onToast, onPeriodLabelChange, onOpenBooking }: { onToast: (message: string) => void; onPeriodLabelChange: (label: string) => void; onOpenBooking: (id: string, date: string) => void }) {
  const [mode, setMode] = useState<'daily' | 'week' | 'month' | 'custom'>('daily')
  const [dailyDate, setDailyDate] = useState(serviceDate())
  return <section className="reports-page">
    <nav className="report-mode-tabs" aria-label="Report period"><button className={mode === 'daily' ? 'active' : ''} onClick={() => setMode('daily')}>Daily</button><button className={mode === 'week' ? 'active' : ''} onClick={() => setMode('week')}>Weekly</button><button className={mode === 'month' ? 'active' : ''} onClick={() => setMode('month')}>Monthly</button><button className={mode === 'custom' ? 'active' : ''} onClick={() => setMode('custom')}>Custom</button></nav>
    {mode === 'daily' ? <DailyReport initialDate={dailyDate} onToast={onToast} onPeriodLabelChange={onPeriodLabelChange} onOpenBooking={onOpenBooking} /> : mode === 'week' ? <WeeklyReport onToast={onToast} onPeriodLabelChange={onPeriodLabelChange} onOpenDaily={date => { setDailyDate(date); setMode('daily') }} /> : mode === 'month' ? <MonthlyReport onToast={onToast} onPeriodLabelChange={onPeriodLabelChange} /> : <LegacyReport mode={mode} onToast={onToast} onPeriodLabelChange={onPeriodLabelChange} />}
  </section>
}

function WeeklyReport({ onToast, onPeriodLabelChange, onOpenDaily }: { onToast: (message: string) => void; onPeriodLabelChange: (label: string) => void; onOpenDaily: (date: string) => void }) {
  const [date,setDate]=useState(serviceDate()); const [view,setView]=useState<WeeklyReportView|null>(null); const [commentary,setCommentary]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const next=await weeklyReportingApi.view(date);setView(next);setCommentary(next.commentary?.managerNotes||'');onPeriodLabelChange(`${formatDate(next.weekStart)} – ${formatDate(next.weekEnd)}`)}catch(loadError){setError(loadError instanceof Error?loadError.message:'Unable to load the Weekly Report.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[date])
  const saveCommentary=async()=>{if(!view)return;setSaving(true);try{const next=await weeklyReportingApi.saveCommentary(view.weekStart,commentary);setView(next);setCommentary(next.commentary?.managerNotes||'');onToast('Weekly commentary saved.')}catch(saveError){onToast(saveError instanceof Error?saveError.message:'Unable to save weekly commentary.')}finally{setSaving(false)}}
  const dayStatus=(status:WeeklyReportView['days'][number]['status'])=>status==='approved'?'Approved':status==='draft'?'Draft':status==='reviewed'?'Reviewed':status==='missing-report'?'Missing Report':status==='in-progress'?'In Progress':'Not Yet Closed'
  const dayName=(value:string)=>new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`))
  const dayValue=(value:number|null)=>value===null?'—':value
  const allOccasions=view?.occasions||[]
  return <div className="weekly-report">
    <section className="weekly-report-header panel"><div className="report-header-main"><div><p className="eyebrow">ANDALUCÍA WEEKLY MANAGEMENT REPORT</p><h2>{view?`${formatDate(view.weekStart)} – ${formatDate(view.weekEnd)}`:'Weekly Report'}</h2><p>Approved Daily snapshots · Monday–Sunday · Maldives service dates</p></div><nav className="report-header-nav" aria-label="Weekly report navigation"><button type="button" aria-label="Previous week" title="Previous week" onClick={()=>setDate(value=>addCalendarDays(value,-7))}>‹</button><input aria-label="Select weekly report date" type="date" value={date} onChange={event=>setDate(event.target.value)}/><button type="button" aria-label="Next week" title="Next week" onClick={()=>setDate(value=>addCalendarDays(value,7))}>›</button></nav></div>{view&&<div className="weekly-authority"><StatusBadge status={view.authority.state==='complete'?'approved':view.authority.state==='no-approved-data'?'missing':'warning'} /><b>{view.authority.label}</b><small>Approved Daily Reports {view.authority.approvedDays} / {view.authority.state==='in-progress'?view.authority.expectedDays:7}{view.authority.state==='in-progress'?' elapsed service days':''}</small></div>}</section>
    {loading&&<div className="panel inline-state">Loading approved Daily authority…</div>}{error&&<div className="panel inline-state error-state">{error}<button className="secondary" onClick={()=>void load()}>Try again</button></div>}
    {!loading&&view&&<>
      <MonthlySection number={1} title="Weekly Performance"><div className="weekly-kpis"><Stat label="Total Covers" value={view.totals.totalCovers}/><Stat label="Total Bookings" value={view.totals.totalBookings}/><Stat label="Kids" value={view.totals.totalKids}/><Stat label="Arrived Covers" value={view.totals.arrivedCovers}/><Stat label="No-show Covers" value={view.totals.noShowCovers} attention={view.totals.noShowCovers>0}/><Stat label="Walk-ins" value={view.totals.walkIns}/><Stat label="Double Dine Pax" value={view.totals.doubleDinePax}/><Stat label="Average Covers / Service Night" value={view.totals.averageCoversPerServiceNight}/></div></MonthlySection>
      <MonthlySection number={2} title="Service Performance by Day"><ReportTable headers={['Day','Status','Covers','Bookings','Kids','Arrived','No-show','Walk-ins','Double Dine','Daily Report']}>{view.days.map(day=><tr key={day.date} className={day.status!=='approved'?'weekly-unapproved':''}><td><b>{dayName(day.date)}</b></td><td><StatusBadge status={day.status==='approved'?'approved':day.status==='draft'?'draft':day.status==='reviewed'?'reviewed':'missing'} /> <small>{dayStatus(day.status)}</small></td><td>{dayValue(day.covers)}</td><td>{dayValue(day.bookings)}</td><td>{dayValue(day.kids)}</td><td>{dayValue(day.arrivedCovers)}</td><td>{dayValue(day.noShowCovers)}</td><td>{dayValue(day.walkIns)}</td><td>{dayValue(day.doubleDinePax)}</td><td><button className="link" onClick={()=>onOpenDaily(day.date)}>View Daily</button></td></tr>)}</ReportTable></MonthlySection>
      <MonthlySection number={3} title="Weekly Revenue"><div className="weekly-revenue"><Stat label="Food Revenue" value={money(view.revenue.foodRevenue)}/><Stat label="Beverage Revenue" value={money(view.revenue.beverageRevenue)}/><Stat label="Wine Revenue" value={money(view.revenue.wineRevenue)}/><Stat label="Liquor Revenue" value={money(view.revenue.liquorRevenue)}/><Stat label="Total Sale" value={money(view.revenue.totalSale)}/><Stat label="Discount" value={money(view.revenue.totalDiscount)}/><Stat label="Void" value={money(view.revenue.totalVoid)}/><Stat label="Net Sale" value={money(view.revenue.netSale)}/><Stat label="Total Revenue" value={money(view.revenue.totalRevenue)}/></div><small className="weekly-source-note">Wine and Liquor are shown as Symphony category values and are not added again to Total Revenue.</small>{view.variances.length>0&&<details className="weekly-variances"><summary>Verified Symphony variances · {view.variances.length}</summary>{view.variances.map(item=><div key={item.date}><b>{dayName(item.date)}</b><span>Net Sale {money(item.netSale)}</span><span>Total Revenue {money(item.totalRevenue)}</span><span>Difference {money(item.difference)}</span><small>{item.verifiedBy}{item.verifiedAt?` · ${new Date(item.verifiedAt).toLocaleString()}`:''}</small></div>)}</details>}</MonthlySection>
      <MonthlySection number={4} title="Chargeable Items / Upselling"><div className="weekly-mini-grid"><Stat label="Total Upsell Revenue" value={money(view.upselling.totalRevenue)}/><Stat label="Items Sold" value={view.upselling.itemsSold}/><Stat label="Top Item" value={view.upselling.topItem}/><Stat label="Top Seller" value={view.upselling.topSeller}/></div><div className="weekly-sources"><span>Chargeable Items <b>{money(view.upselling.chargeableRevenue)}</b></span><span>Wine / Spirits <b>{money(view.upselling.wineSpiritsRevenue)}</b></span></div></MonthlySection>
      <MonthlySection number={5} title="Guest Experience"><div className="weekly-occasion-grid">{allOccasions.length?allOccasions.map(item=><article key={item.key}><span>{item.label}</span><b>{item.count}</b><small>{item.covers} covers</small></article>):<Empty/>}</div></MonthlySection>
      <MonthlySection number={6} title="Service Attention"><div className="weekly-attention"><Stat label="No-show Covers" value={view.attention.noShowCovers}/><Stat label="No-show Rate" value={view.attention.noShowRate===null?'—':`${view.attention.noShowRate}%`}/><Stat label="Walk-ins" value={view.attention.walkIns}/><Stat label="Double Dine Pax" value={view.attention.doubleDinePax}/><Stat label="Highest No-show Day" value={view.attention.highestNoShowDay?dayName(view.attention.highestNoShowDay):'—'}/><Stat label="Highest Covers Day" value={view.attention.highestCoversDay?dayName(view.attention.highestCoversDay):'—'}/><Stat label="Busiest Service Day" value={view.attention.busiestServiceDay?dayName(view.attention.busiestServiceDay):'—'}/></div></MonthlySection>
      <MonthlySection number={7} title="Previous Week Comparison">{view.comparison.available?<ReportTable headers={['Metric','Current Week','Previous Week','Difference','Change']}>{view.comparison.metrics.map(item=><tr key={item.key}><td><b>{item.label}</b></td><td>{item.key==='revenue'||item.key==='upsell'?money(item.current):item.current}</td><td>{item.key==='revenue'||item.key==='upsell'?money(item.previous):item.previous}</td><td>{item.key==='revenue'||item.key==='upsell'?money(item.difference):item.difference}</td><td>{item.changePercent===null?'—':`${item.changePercent}%`}</td></tr>)}</ReportTable>:<div className="weekly-unavailable"><b>Previous Week Comparison Unavailable</b><span>{view.comparison.reason}</span></div>}</MonthlySection>
      <MonthlySection number={8} title="Weekly Commentary"><textarea className="weekly-commentary" value={commentary} onChange={event=>setCommentary(event.target.value)} placeholder="Add management context for this weekly view…"/><div className="manager-summary-actions weekly-commentary-actions"><small>Commentary is audited context and does not alter approved Daily authority.</small><div><button className="secondary" onClick={()=>window.print()}>Print / Export</button><button className="primary" disabled={saving} onClick={()=>void saveCommentary()}>{saving?'Saving…':'Save Commentary'}</button></div></div></MonthlySection>
      <MonthlySection number={9} title="Weekly Report Completeness"><div className="weekly-completeness aligned"><div><b>{view.authority.approvedDays} of 7 Daily reports approved</b><span>{view.authority.label}</span></div><div>{view.status.map(item=><span className={item.state} key={item.label}><i/>{item.label}<small>{item.detail}</small></span>)}</div></div></MonthlySection>
    </>}
  </div>
}

type MonthlyComparisonMetric=MonthlyReportView['comparison']['metrics'][number]
const percent=(value:string|null)=>value===null?'Not entered':`${Number(value).toFixed(2)}%`
const comparisonValue=(metric:MonthlyComparisonMetric|undefined,currency=false,percentage=false)=>metric?currency?money(metric.previous):percentage?`${metric.previous.toFixed(2)}%`:metric.previous:'—'
function MonthlyTrend({label,value,metric,currency=false,percentage=false,favorable='up',text=false}:{label:string;value:ReactNode;metric?:MonthlyComparisonMetric;currency?:boolean;percentage?:boolean;favorable?:'up'|'down'|'neutral';text?:boolean}){
  const direction=!metric||metric.difference===0?'flat':metric.difference>0?'up':'down',tone=!metric||direction==='flat'||favorable==='neutral'?'neutral':direction===favorable?'positive':'negative'
  return <article className={`monthly-trend-card ${tone}${text?' text-value':''}`}><span>{label}</span><strong>{value}</strong>{metric?<div className="monthly-trend"><b aria-label={direction==='up'?'Increased':direction==='down'?'Decreased':'Unchanged'}>{direction==='up'?'↑':direction==='down'?'↓':'→'} {metric.changePercent===null?'New':`${Math.abs(metric.changePercent).toFixed(1)}%`}</b><small>vs {comparisonValue(metric,currency,percentage)}</small></div>:<small className="monthly-trend-unavailable">Previous month unavailable</small>}</article>
}
function MonthlySection({number,title,children,collapsible=false,open=false,id,meta}:{number:number;title:string;children:ReactNode;collapsible?:boolean;open?:boolean;id?:string;meta?:ReactNode}){
  if(collapsible)return <details id={id} className="monthly-dashboard-section panel monthly-collapsible" open={open}><summary><i>{number}</i><span>{title}</span><b aria-hidden="true">⌄</b></summary><div className="monthly-section-body">{children}</div></details>
  return <section id={id} className="monthly-dashboard-section panel"><header><i>{number}</i><h3>{title}</h3>{meta&&<div className="monthly-section-meta">{meta}</div>}</header><div className="monthly-section-body">{children}</div></section>
}

function MonthlyReport({onToast,onPeriodLabelChange}:{onToast:(message:string)=>void;onPeriodLabelChange:(label:string)=>void}){
  const [month,setMonth]=useState(serviceDate().slice(0,7)),[view,setView]=useState<MonthlyReportView|null>(null),[finance,setFinance]=useState<MonthlyFinancePayload>(blankMonthlyFinance()),[commentary,setCommentary]=useState(''),[followUps,setFollowUps]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const next=await monthlyReportingApi.view(month);setView(next);setFinance(next.finance.input?.financePayload||blankMonthlyFinance());setCommentary(next.finance.input?.managerCommentary||'');setFollowUps(next.finance.input?.followUpsChanges||'');onPeriodLabelChange(new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${next.monthStart}T00:00:00Z`)))}catch(loadError){setError(loadError instanceof Error?loadError.message:'Unable to load the Monthly Report.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[month])
  const changeMonth=(months:number)=>setMonth(addCalendarMonths(`${month}-01`,months).slice(0,7)),update=(field:MonthlyFinanceField,value:string)=>setFinance(current=>({...current,[field]:value===''?null:value.replace(/[^\d.-]/g,'')}))
  const save=async()=>{setSaving(true);try{const next=await monthlyReportingApi.save(month,{expectedRevision:view?.finance.input?.revisionNumber??null,financePayload:finance,managerCommentary:commentary,followUpsChanges:followUps});setView(next);setFinance(next.finance.input?.financePayload||blankMonthlyFinance());onToast('Monthly Finance and management context saved.')}catch(saveError){const message=saveError instanceof Error?saveError.message:'Unable to save Monthly Report inputs.';setError(message);onToast(message)}finally{setSaving(false)}}
  const verify=async()=>{if(!view?.finance.input)return;setSaving(true);try{const next=await monthlyReportingApi.verify(month,view.finance.input.revisionNumber);setView(next);setFinance(next.finance.input?.financePayload||finance);onToast('Monthly Finance verified.')}catch(saveError){const message=saveError instanceof Error?saveError.message:'Unable to verify Monthly Finance.';setError(message);onToast(message)}finally{setSaving(false)}}
  const day=(value:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`)),field=(key:MonthlyFinanceField,label:string,suffix='')=><label key={key}>{label}<span className="monthly-input"><input inputMode="decimal" placeholder="Not entered" value={finance[key]??''} onChange={event=>update(key,event.target.value)}/>{suffix&&<i>{suffix}</i>}</span></label>
  const food=finance,financeStatus=view?.finance.input?.financeStatus||'not_entered',occasions=view?.occasions||[],occasionCount=occasions.reduce((sum,item)=>sum+item.count,0),varianceTotal=view?.variances.reduce((sum,item)=>sum+Math.abs(Number(item.difference)),0)||0,metric=(key:string)=>view?.comparison.available?view.comparison.metrics.find(item=>item.key===key):undefined
  return <div className="monthly-report">
    <section className="monthly-report-header panel"><div className="monthly-header-main"><div><p className="eyebrow">ANDALUCÍA MONTHLY MANAGEMENT REPORT</p><h2>{new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${month}-01T00:00:00Z`))}</h2><p>Approved Daily snapshots · verified month-end Finance</p></div><nav className="monthly-header-nav" aria-label="Monthly report navigation"><button type="button" aria-label="Previous month" title="Previous month" onClick={()=>changeMonth(-1)}>‹</button><button type="button" aria-label="Next month" title="Next month" onClick={()=>changeMonth(1)}>›</button></nav></div>{view&&<div className="monthly-authority"><StatusBadge status={view.overallStatus==='MONTHLY REPORT READY'?'approved':view.overallStatus==='FINANCE PENDING'?'warning':'in-progress'}/><b>{view.overallStatus}</b><small>{view.authority.approvedDays} / {view.authority.expectedDays} service nights approved</small></div>}</section>
    {loading&&<div className="panel inline-state">Loading approved Monthly authority…</div>}{error&&<div className="panel inline-state error-state">{error}<button className="secondary" onClick={()=>void load()}>Try again</button></div>}
    {!loading&&view&&<>
      <MonthlySection number={1} title="Performance Overview"><div className="monthly-dashboard-grid performance"><MonthlyTrend label="Total Covers" value={view.totals.totalCovers} metric={metric('covers')}/><MonthlyTrend label="Avg Covers / Night" value={view.totals.averageCoversPerServiceNight} metric={metric('averageCovers')}/><MonthlyTrend label="Total Bookings" value={view.totals.totalBookings} metric={metric('bookings')}/><MonthlyTrend label="Kids" value={view.totals.totalKids} metric={metric('kids')}/><MonthlyTrend label="No-show Covers" value={view.totals.noShowCovers} metric={metric('noShows')} favorable="down"/><MonthlyTrend label="Double Dine Pax" value={view.totals.doubleDinePax} metric={metric('doubleDine')}/><MonthlyTrend label="Walk-ins" value={view.totals.walkIns} metric={metric('walkIns')} favorable="neutral"/></div><div className="monthly-insight-strip"><span><b>{view.authority.approvedDays} / {view.authority.expectedDays}</b> service nights approved</span><span><b>{view.attention.noShowRate===null?'—':`${view.attention.noShowRate}%`}</b> no-show rate</span><span><b>{view.attention.busiestServiceDay?day(view.attention.busiestServiceDay):'—'}</b> busiest service day</span></div></MonthlySection>
      <MonthlySection number={2} title="Revenue Performance"><div className="monthly-dashboard-grid revenue">{(['foodRevenue','beverageRevenue','totalRevenue','netSale','totalSale','wineRevenue','liquorRevenue','totalDiscount','totalVoid'] as const).map(key=><MonthlyTrend key={key} label={labelKey(key)} value={money(view.revenue[key])} metric={metric(key)} currency/>)}</div><small className="weekly-source-note">Wine and Liquor are Beverage Revenue breakdowns and are not added again to Total Revenue.</small>{view.variances.length>0&&<details className="weekly-variances"><summary>Verified Symphony Variance · {view.variances.length} affected days · {money(varianceTotal)} absolute variance</summary>{view.variances.map(item=><div key={item.date}><b>{day(item.date)}</b><span>Net Sale {money(item.netSale)}</span><span>Total Revenue {money(item.totalRevenue)}</span><span>Difference {money(item.difference)}</span><small>{item.verifiedBy}{item.verifiedAt?` · ${new Date(item.verifiedAt).toLocaleString()}`:''}</small></div>)}</details>}</MonthlySection>
      <MonthlySection number={3} title="Chargeable Items / Upselling"><div className="monthly-dashboard-grid upselling"><MonthlyTrend label="Total Upsell Revenue" value={money(view.upselling.totalRevenue)} metric={metric('upsell')} currency/><MonthlyTrend label="Items Sold" value={view.upselling.itemsSold} metric={metric('upsellItems')}/><MonthlyTrend label="Top Item" value={view.upselling.topItem} text/><MonthlyTrend label="Top Seller" value={view.upselling.topSeller} text/></div><div className="weekly-sources"><span>Chargeable Items <b>{money(view.upselling.chargeableRevenue)}</b></span><span>Wine / Spirits <b>{money(view.upselling.wineSpiritsRevenue)}</b></span></div>{view.upselling.topItems.length>0&&<details className="monthly-breakdown"><summary>View Item Breakdown</summary><div>{view.upselling.topItems.map(item=><span key={item.label}><b>{item.label}</b><small>{item.quantity} sold · {money(item.revenue)}</small></span>)}</div></details>}</MonthlySection>
      <MonthlySection number={4} title="Guest Experience & Guest Mix"><div className="monthly-occasion-grid">{occasions.map(item=><article key={item.key}><span>{item.label}</span><b>{item.count}</b><small>{item.covers} pax</small>{metric(`occasion:${item.key}`)&&<em>{metric(`occasion:${item.key}`)!.difference>0?'↑':metric(`occasion:${item.key}`)!.difference<0?'↓':'→'} {metric(`occasion:${item.key}`)!.changePercent===null?'New':`${Math.abs(metric(`occasion:${item.key}`)!.changePercent!).toFixed(1)}%`} · vs {metric(`occasion:${item.key}`)!.previous}</em>}</article>)}</div><small>{occasionCount} occasions · all nine categories shown · no room lists in Monthly reporting</small></MonthlySection>
      <MonthlySection number={5} title="Team & Development" collapsible><div className="monthly-dashboard-grid team"><MonthlyTrend label="Team Size" value={view.staffing.currentTeamSize}/><MonthlyTrend label="Avg Staff On Duty / Day" value={view.staffing.averageOnDuty}/><MonthlyTrend label="OFF Days" value={view.staffing.offDays}/><MonthlyTrend label="Annual Leave" value={view.staffing.annualLeaveDays}/><MonthlyTrend label="Public Holidays" value={view.staffing.publicHolidays}/><MonthlyTrend label="Sick Leave" value={view.staffing.sickLeaveDays}/><MonthlyTrend label="Training Sessions" value={view.training.sessions}/><MonthlyTrend label="Participants" value={view.training.participants}/><MonthlyTrend label="Training Hours" value="Unavailable" text/></div></MonthlySection>
      <MonthlySection number={6} title="Maintenance & Follow-up" collapsible><div className="monthly-dashboard-grid maintenance"><MonthlyTrend label="Opened" value={view.maintenance.opened}/><MonthlyTrend label="Completed" value={view.maintenance.completed}/><MonthlyTrend label="In Progress" value={view.maintenance.inProgress}/><MonthlyTrend label="Unresolved" value={view.maintenance.unresolved} favorable="down"/></div>{view.maintenance.items.length>0&&<div className="monthly-maintenance-list"><h4>Key Maintenance Items</h4>{view.maintenance.items.map(item=><article key={item.id}><div><b>{item.issue}</b><small>{item.area}</small></div><span>{item.status}</span></article>)}</div>}</MonthlySection>
      <MonthlySection number={7} title="Cost Control & Finance">
        <div className="monthly-finance-heading"><div><StatusBadge status={financeStatus}/>{view.finance.input?.verifiedByName&&<small>Verified by {view.finance.input.verifiedByName} · {view.finance.input.verifiedAt?new Date(view.finance.input.verifiedAt).toLocaleString():'—'}</small>}</div><small>Explicit zero values are preserved separately from Not Entered.</small></div>
        <div className="monthly-cost-grid">
          <section><h4>Food Cost Control</h4><div className="monthly-primary-metrics"><Detail label="Actual Food Cost %" value={percent(food.mtdFoodCostPercent)}/><Detail label="Budget %" value={percent(food.budgetFoodCostPercent)}/><Detail label="Variance" value={food.foodCostVariancePercent===null?'—':percent(food.foodCostVariancePercent)}/></div><div className="monthly-finance-fields">{field('netFoodCost','Net Food Cost')}{field('foodSales','Food Sales')}{field('mtdFoodCostPercent','MTD Food Cost %','%')}{field('budgetFoodCostPercent','Budget Food Cost %','%')}{field('foodCostPerCover','Food Cost Per Cover')}{field('foodRequisitions','Total Food Request')}</div><CostCrossCheck name="Food" entered={food.enteredFoodCostPercent} calculated={food.calculatedFoodCostPercent} difference={food.foodCostPercentDifference} matched={view.finance.foodMatched}/></section>
          <section><h4>Beverage Cost Control</h4><div className="monthly-primary-metrics"><Detail label="Actual Beverage Cost %" value={percent(food.mtdBeverageCostPercent)}/><Detail label="Budget %" value={percent(food.budgetBeverageCostPercent)}/><Detail label="Variance" value={food.beverageCostVariancePercent===null?'—':percent(food.beverageCostVariancePercent)}/></div><div className="monthly-finance-fields">{field('netBeverageCost','Net Beverage Cost')}{field('beverageSales','Beverage Sales')}{field('mtdBeverageCostPercent','MTD Beverage Cost %','%')}{field('budgetBeverageCostPercent','Budget Beverage Cost %','%')}{field('beverageCostPerCover','Beverage Cost Per Cover')}{field('beverageRequisitions','Total Beverage Request')}</div><CostCrossCheck name="Beverage" entered={food.enteredBeverageCostPercent} calculated={food.calculatedBeverageCostPercent} difference={food.beverageCostPercentDifference} matched={view.finance.beverageMatched}/></section>
        </div>
        <details className="monthly-finance-details"><summary>Loss & Control</summary><div className="monthly-finance-fields">{field('breakages','Breakages')}{field('foodWastage','Food Wastage')}{field('beverageWastage','Beverage Wastage')}{field('beverageSpoilage','Beverage Spoilage')}</div></details>
        <div className="monthly-finance-actions"><button className="secondary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save Finance Inputs'}</button><button className="primary" disabled={saving||!view.finance.complete||!view.finance.input} onClick={()=>void verify()}>✓ Verified Against Finance Report</button></div>
      </MonthlySection>
      <MonthlySection number={8} title="Previous Month Comparison" collapsible>{view.comparison.available?<><ReportTable headers={['Metric','Current','Previous','Difference','Change']}>{view.comparison.metrics.filter(item=>!item.key.startsWith('occasion:')).map(item=><tr key={item.key}><td><b>{item.label}</b></td><td>{/Revenue|Cost \/ Cover/.test(item.label)?money(item.current):item.current}</td><td>{/Revenue|Cost \/ Cover/.test(item.label)?money(item.previous):item.previous}</td><td>{/Revenue|Cost \/ Cover/.test(item.label)?money(item.difference):item.difference}</td><td>{item.changePercent===null?'New from zero':`${item.changePercent.toFixed(1)}%`}</td></tr>)}</ReportTable>{!view.comparison.financeAvailable&&<small className="comparison-note">Finance comparison requires both months to be verified.</small>}</>:<div className="weekly-unavailable"><b>Previous month unavailable</b><span>{view.comparison.reason}</span></div>}</MonthlySection>
      <MonthlySection number={9} title="Manager's Monthly Review"><div className="monthly-review-grid"><label><b>Performance Summary</b><textarea value={commentary} onChange={event=>setCommentary(event.target.value)} placeholder="Summarize performance, guest experience, people and cost control…"/></label><label><b>Priorities for Next Month</b><textarea value={followUps} onChange={event=>setFollowUps(event.target.value)} placeholder="Record follow-ups, changes and next-month priorities…"/></label></div><div className="monthly-review-print"><article><b>Performance Summary</b><p>{commentary||'Not entered'}</p></article><article><b>Priorities for Next Month</b><p>{followUps||'Not entered'}</p></article></div><div className="monthly-context-actions"><button className="secondary" onClick={()=>window.print()}>Print / Export</button><button className="primary" disabled={saving} onClick={()=>void save()}>Save Monthly Review</button></div>{view.legacyCommentary&&<div className="monthly-legacy"><b>Preserved Legacy Commentary</b><p>{view.legacyCommentary.managerNotes}</p></div>}</MonthlySection>
      <section className="monthly-readiness-panel panel"><details open={view.readiness.some(item=>item.state!=='complete')}><summary><div><p className="eyebrow">MANAGEMENT CONTROL</p><h3>Monthly Report Readiness</h3></div><b>{view.readiness.filter(item=>item.state==='complete').length} / {view.readiness.length}</b></summary><div className="monthly-readiness">{view.readiness.map(item=><article className={item.state} key={item.label}><StatusBadge status={item.state}/><div><b>{item.label}</b><small>{item.detail}</small></div></article>)}</div></details></section>
    </>}
  </div>
}

function CostCrossCheck({name,entered,calculated,difference,matched}:{name:string;entered:string|null;calculated:string|null;difference:string|null;matched:boolean|null}){return <div className={`monthly-crosscheck ${matched===false?'variance':matched?'matched':''}`}><b>{matched===false?'COST % VARIANCE — VERIFY AGAINST FINANCE':matched?'✓ COST % MATCHED':`${name.toUpperCase()} COST % CROSS-CHECK`}</b><span>Entered Finance % <strong>{entered===null?'—':`${Number(entered).toFixed(2)}%`}</strong></span><span>Calculated % <strong>{calculated===null?'—':`${Number(calculated).toFixed(2)}%`}</strong></span><span>Difference <strong>{difference===null?'—':`${Number(difference).toFixed(2)}%`}</strong></span></div>}

function DailyReport({ initialDate, onToast, onPeriodLabelChange, onOpenBooking }: { initialDate?: string; onToast: (message: string) => void; onPeriodLabelChange: (label: string) => void; onOpenBooking: (id: string, date: string) => void }) {
  const [date, setDate] = useState(initialDate || serviceDate()); const [view, setView] = useState<DailyReportView | null>(null); const [manual, setManual] = useState<DailyReportManualPayload>(blankManual())
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [approvalOpen, setApprovalOpen] = useState(false)
  const load = async () => { setLoading(true); setError(''); try { const next = await dailyReportingApi.view(date); setView(next); setManual(next.report?.manualPayload || blankManual()); setApprovalOpen(next.report?.status === 'reviewed') } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load the Daily Report.') } finally { setLoading(false) } }
  useEffect(() => { onPeriodLabelChange(formatDate(date)); void load() }, [date])
  const editable = Boolean(view?.editable)
  const updateSymphony = (key: keyof DailyReportManualPayload['symphony'], value: string | DailyReportVoidDetail[]) => setManual(current => ({ ...current, symphony: { ...current.symphony, [key]: value }, revenueVerification: { acknowledged: false } }))
  const updateVerification = (value: Partial<DailyReportManualPayload['serviceVerification']>) => setManual(current => ({ ...current, serviceVerification: { ...current.serviceVerification, ...value } }))
  const updateManagerSummary = (value: string) => setManual(current => ({ ...current, manager: { ...current.manager, operationSummary: value } }))
  const updateRevenueVerification = (acknowledged: boolean) => setManual(current => ({ ...current, revenueVerification: { acknowledged } }))
  const save = async () => { setSaving(true); try { const next = await dailyReportingApi.saveDraft(date, manual); setView(next); setManual(next.report?.manualPayload || manual); onToast('Daily Report draft saved.'); return next } catch (saveError) { onToast(saveError instanceof Error ? saveError.message : 'Unable to save the Daily Report.'); return null } finally { setSaving(false) } }
  const review = async () => { const saved = await save(); if (!saved) return; setSaving(true); try { const next = await dailyReportingApi.review(date); setView(next); setManual(next.report?.manualPayload || manual); setApprovalOpen(true); onToast('Daily Report marked Reviewed.') } catch (reviewError) { onToast(reviewError instanceof Error ? reviewError.message : 'Daily Report is not ready for review.'); await load() } finally { setSaving(false) } }
  const approve = async () => { if (!view?.report) return; setSaving(true); try { const next = await dailyReportingApi.approve(date, `daily-${view.report.id}-${view.report.revisionNumber}`); setView(next); setApprovalOpen(false); onToast('Daily Report approved and frozen.') } catch (approvalError) { onToast(approvalError instanceof Error ? approvalError.message : 'Unable to approve the Daily Report.'); await load() } finally { setSaving(false) } }
  const voidSubtotal = manual.symphony.voidDetails.reduce((sum, row) => sum + Number(row.amount || 0), 0); const doubleSubtotal = manual.serviceVerification.details.reduce((sum, row) => sum + Number(row.pax || 0), 0); const content = view?.content
  const reportReady = Boolean(view && view.readiness.every(item => !item.blocking && !item.verificationRequired && item.state === 'complete'))
  return <>
    <section className="daily-report-header panel"><div className="report-header-main"><div><p className="eyebrow">ANDALUCÍA DAILY OPERATIONS REPORT</p><h2>{formatDate(date)}</h2><p>Authoritative nightly operational report</p></div><nav className="report-header-nav" aria-label="Daily report navigation"><button type="button" aria-label="Previous day" title="Previous day" onClick={()=>setDate(value=>addCalendarDays(value,-1))}>‹</button><input aria-label="Select Daily Report service date" type="date" value={date} onChange={event=>setDate(event.target.value)}/><button type="button" aria-label="Next day" title="Next day" onClick={()=>setDate(value=>addCalendarDays(value,1))}>›</button></nav></div><StatusBadge status={view?.report?.status || 'not-started'} /></section>
    {loading && <div className="panel inline-state">Loading authoritative operational data…</div>}{error && <div className="panel inline-state error-state">{error}<button className="secondary" onClick={() => void load()}>Try again</button></div>}
    {!loading && content && view && <>
      <MonthlySection id="daily-service" number={1} title="Performance Overview"><div className="daily-kpis"><Stat label="Total Covers" value={content.servicePerformance.totalCovers} /><Stat label="Adults" value={content.servicePerformance.adults} /><Stat label="Kids" value={content.servicePerformance.kids} /><Stat label="Total Bookings" value={content.servicePerformance.totalBookings} /><Stat label="Arrived Covers" value={content.servicePerformance.arrivedCovers} /><Stat label="No-show Covers" value={content.servicePerformance.noShowCovers} attention={content.servicePerformance.noShowCovers > 0} /><Stat label="No-show Rooms" value={<RoomList rooms={content.servicePerformance.noShowRooms} />} /><Stat label="Walk-ins" value={content.servicePerformance.walkIns} /></div></MonthlySection>
      <MonthlySection id="daily-time" number={2} title="Booking by Time Slot"><ReportTable headers={['Time', 'Bookings', 'Covers', 'Adults', 'Kids', 'No-shows', 'Status']}>{content.servicePerformance.bookingByTimeSlot.map(item => <tr key={item.time}><td><b>{bookingTimeWindow(item.time)}</b></td><td>{item.bookings}</td><td>{item.covers}</td><td>{item.adults}</td><td>{item.kids}</td><td>{item.noShows}</td><td>{item.status}</td></tr>)}</ReportTable>{!content.servicePerformance.bookingByTimeSlot.length && <Empty />}</MonthlySection>
      <MonthlySection id="daily-symphony" number={3} title="Symphony / Revenue"><fieldset disabled={!editable}><div className="symphony-groups"><FinancialGroup title="Revenue" fields={['foodRevenue', 'beverageRevenue']} manual={manual} update={updateSymphony} /><FinancialGroup title="Beverage Breakdown" help="Wine and Liquor are supporting breakdowns of Beverage Revenue—not additional revenue." fields={['wineRevenue', 'liquorRevenue']} manual={manual} update={updateSymphony} /><FinancialGroup title="Sales Reconciliation" fields={['totalSale', 'totalDiscount', 'totalVoid', 'netSale', 'totalRevenue']} manual={manual} update={updateSymphony} /></div>{view.revenueReconciliation.status !== 'incomplete' && view.revenueReconciliation.status !== 'reconciled' && <section className={`revenue-variance ${view.revenueReconciliation.status}`}><div><p className="eyebrow">REVENUE VARIANCE — VERIFY AGAINST SYMPHONY</p><div className="variance-values"><Detail label="Net Sale" value={money(view.revenueReconciliation.netSale || 0)} /><Detail label="Total Revenue" value={money(view.revenueReconciliation.totalRevenue || 0)} /><Detail label="Difference" value={money(view.revenueReconciliation.difference || 0)} /></div><p>{view.revenueReconciliation.messages.join(' ')}</p></div><label className="variance-check"><input type="checkbox" checked={manual.revenueVerification?.acknowledged === true} onChange={event => updateRevenueVerification(event.target.checked)} /> Verified against Symphony</label>{view.revenueReconciliation.status === 'verified-with-variance' && <small>Verified by {view.revenueReconciliation.verifiedByName}{view.revenueReconciliation.verifiedAt ? ` · ${new Date(view.revenueReconciliation.verifiedAt).toLocaleString()}` : ''}</small>}</section>}<VoidEditor rows={manual.symphony.voidDetails} subtotal={voidSubtotal} onChange={rows => updateSymphony('voidDetails', rows)} /></fieldset></MonthlySection>
      <MonthlySection id="daily-verification" number={4} title="Service Verification"><fieldset disabled={!editable}>{editable ? <div className="double-dine-compact"><label className="primary-number">Double Dine Pax<input type="number" min="0" step="1" value={manual.serviceVerification.doubleDinePax ?? ''} placeholder="Not entered" onChange={event => updateVerification({ doubleDinePax: event.target.value === '' ? null : Number(event.target.value) })} /></label><div className="double-dine-subtotal"><span>Detail Subtotal</span><b>{doubleSubtotal}</b></div><button type="button" className="secondary" onClick={() => updateVerification({ details: [...manual.serviceVerification.details, { roomNumber:'', pax:1, sourceOutlet:'', note:'' }] })}>＋ Add Details</button></div> : <div className="double-dine-compact double-dine-readonly"><div className="double-dine-primary"><span>Double Dine Pax</span><b>{manual.serviceVerification.doubleDinePax ?? 'Not entered'}</b></div><div className="double-dine-subtotal"><span>Detail Subtotal</span><b>{doubleSubtotal}</b></div></div>}<small className="double-dine-help">Separate from Total Covers. Enter 0 when genuinely none.</small>{manual.serviceVerification.details.length > 0 && (editable ? <DoubleDineEditor rows={manual.serviceVerification.details} subtotal={doubleSubtotal} total={manual.serviceVerification.doubleDinePax} onChange={details => updateVerification({ details })} /> : <DoubleDineReadOnly rows={manual.serviceVerification.details} subtotal={doubleSubtotal} total={manual.serviceVerification.doubleDinePax} />)}</fieldset></MonthlySection>
      <MonthlySection id="daily-upselling" number={5} title="Chargeable Items / Upselling"><div className="upsell-summary"><Stat label="Total Upsell Revenue" value={money(content.upselling.totalUpsellRevenue)} /><Stat label="Items Sold" value={content.upselling.itemsSold} /><Stat label="Top Item" value={content.upselling.topItem} /><Stat label="Top Seller" value={content.upselling.topSeller} /></div><ReportTable headers={['Item / Bottle', 'Qty', 'Sold By', 'Room', 'Check / Invoice', 'Amount', 'Source']}>{content.upselling.details.map(row => <tr key={`${row.source}-${row.id}`}><td>{row.item}</td><td>{row.quantity}</td><td>{row.soldBy}{row.staffNumber && <small>{row.staffNumber}</small>}</td><td>{row.roomNumber || '—'}</td><td>{row.checkInvoiceNumber || '—'}</td><td>{money(row.amount)}</td><td>{row.source}</td></tr>)}</ReportTable>{!content.upselling.details.length && <Empty />}</MonthlySection>
      <MonthlySection id="daily-occasions" number={6} title="Guest Experience"><div className="occasion-room-grid">{content.guestOccasions.categories.map(category => { const rooms = content.guestOccasions.roomDetails.filter(row => row.category === category.key || row.label.toLowerCase() === category.label.toLowerCase()); return <article key={category.key}><header><b>{category.label}</b><span>{category.count} · {category.covers} pax</span></header><div>{rooms.slice(0, 8).map(room => <button key={room.occasionId} disabled={!room.bookingId} title={`${room.guestName} · ${room.covers} pax`} onClick={() => room.bookingId && onOpenBooking(room.bookingId, date)}>{room.roomNumber || 'No room'} × {room.covers || '—'}</button>)}{rooms.length > 8 && <small>+ {rooms.length - 8} more rooms</small>}{!rooms.length && <small>No occasions</small>}</div></article> })}</div></MonthlySection>
      <MonthlySection id="daily-manager" number={7} title="Manager's Operation Summary"><fieldset disabled={!editable}><label>Operation Summary <span>Required</span><textarea rows={5} value={manual.manager.operationSummary} onChange={event => updateManagerSummary(event.target.value)} placeholder="Record the service outcome, important context and next-morning priorities." /></label></fieldset></MonthlySection>
      <MonthlySection id="daily-readiness" number={8} title="Report Readiness / Approval" meta={<><span>{reportReady?'REPORT READY ✓':'MANAGEMENT CONTROL'}</span><b>{view.readiness.filter(item=>item.state==='complete').length} / {view.readiness.length}</b></>}><DailyReadinessGrid items={view.readiness} /><div className="daily-actions final-report-actions">{editable && <button className="secondary" disabled={saving} onClick={() => void save()}>Save Draft</button>}{editable && view.report?.status !== 'reviewed' && <button className="primary" disabled={saving} onClick={() => void review()}>Review Report</button>}{view.report?.status === 'reviewed' && <button className="primary approval-action" disabled={saving || view.revenueReconciliation.status === 'verification-required'} title={view.revenueReconciliation.status === 'verification-required' ? 'Verify the Symphony revenue variance before approval.' : undefined} onClick={() => setApprovalOpen(true)}>Approve Report</button>}<button className="secondary" onClick={() => window.print()}>Print / Export</button></div><DailyAuditEvidence report={view.report} /></MonthlySection>
      {approvalOpen && <ApprovalDialog view={view} manual={manual} onClose={() => setApprovalOpen(false)} onApprove={() => void approve()} saving={saving} />}
    </>}
  </>
}

function FinancialGroup({ title, help, fields, manual, update }: { title: string; help?: string; fields: Array<keyof DailyReportManualPayload['symphony']>; manual: DailyReportManualPayload; update: (key: keyof DailyReportManualPayload['symphony'], value: string) => void }) { return <section><h4>{title}</h4>{help && <p>{help}</p>}{fields.map(key => <label key={key}>{labelKey(key)}<span className="money-input"><i>$</i><input inputMode="decimal" placeholder="Not entered" value={String(manual.symphony[key])} onChange={event => update(key, event.target.value.replace(/[^\d.]/g, ''))} /></span></label>)}</section> }
function VoidEditor({ rows, subtotal, onChange }: { rows: DailyReportVoidDetail[]; subtotal: number; onChange: (rows: DailyReportVoidDetail[]) => void }) { const update = (index: number, value: Partial<DailyReportVoidDetail>) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...value } : row)); return <section className="detail-editor"><div className="detail-editor-title"><div><h4>Void Details</h4><small>Required when Total Void is greater than zero · Detail subtotal {money(subtotal)}</small></div><button type="button" className="secondary" onClick={() => onChange([...rows, { amount: '', reason: '', checkInvoiceNumber: '' }])}>＋ Add Void</button></div>{rows.map((row,index) => <div className="detail-row void-row" key={index}><label>Amount<input inputMode="decimal" value={row.amount} onChange={event => update(index,{ amount:event.target.value.replace(/[^\d.]/g,'') })} /></label><label>Reason<input value={row.reason} onChange={event => update(index,{ reason:event.target.value })} /></label><label>Check / Invoice<input value={row.checkInvoiceNumber} onChange={event => update(index,{ checkInvoiceNumber:event.target.value })} /></label><button type="button" className="link danger" onClick={() => onChange(rows.filter((_,rowIndex) => rowIndex !== index))}>Remove</button></div>)}</section> }
function DoubleDineEditor({ rows, subtotal, total, onChange }: { rows: DailyReportDoubleDineDetail[]; subtotal: number; total: number | null; onChange: (rows: DailyReportDoubleDineDetail[]) => void }) { const update = (index: number, value: Partial<DailyReportDoubleDineDetail>) => onChange(rows.map((row,rowIndex) => rowIndex === index ? { ...row,...value } : row)); const mismatch = total !== null && subtotal !== total; return <section className="detail-editor double-dine-details"><h4>Double Dine Details</h4>{mismatch && <small className="warning-text">Detail subtotal {subtotal} differs from entered total {total}.</small>}{rows.map((row,index) => <div className="detail-row double-row" key={index}><label>Room<input value={row.roomNumber} onChange={event => update(index,{roomNumber:event.target.value})} /></label><label>Pax<input type="number" min="1" step="1" value={row.pax} onChange={event => update(index,{pax:Number(event.target.value)})} /></label><label>Source / Outlet<input value={row.sourceOutlet} onChange={event => update(index,{sourceOutlet:event.target.value})} /></label><label>Note<input value={row.note} onChange={event => update(index,{note:event.target.value})} /></label><button type="button" className="link danger" onClick={() => onChange(rows.filter((_,rowIndex) => rowIndex !== index))}>Remove</button></div>)}</section> }
function DoubleDineReadOnly({ rows, subtotal, total }: { rows: DailyReportDoubleDineDetail[]; subtotal: number; total: number | null }) { const mismatch = total !== null && subtotal !== total; return <section className="double-dine-details double-dine-report"><h4>Double Dine Details</h4>{mismatch && <small className="warning-text">Detail subtotal {subtotal} differs from entered total {total}.</small>}<div className="double-dine-report-grid"><b>Room</b><b>Pax</b><b>Source / Outlet</b><b>Note</b>{rows.map((row,index) => <Fragment key={`${row.roomNumber}-${index}`}><span>{row.roomNumber || '—'}</span><span>{row.pax}</span><span>{row.sourceOutlet || '—'}</span><span>{row.note || '—'}</span></Fragment>)}</div></section> }
function DailyAuditEvidence({ report }: { report: DailyReportView['report'] }) { if (!report) return null; return <footer className="daily-audit-evidence"><div><small>Prepared · <b>{report.preparedByName}</b> · {new Date(report.preparedAt).toLocaleString()}</small>{report.reviewedByName && <small>Reviewed · <b>{report.reviewedByName}</b> · {new Date(report.reviewedAt!).toLocaleString()}</small>}{report.approvedByName && <small>Approved · <b>{report.approvedByName}</b> · {new Date(report.approvedAt!).toLocaleString()}</small>}</div>{report.status === 'approved' && <div className="approved-lock compact"><b>✓ APPROVED · FROZEN SNAPSHOT</b><span>Report values are locked from live operational changes.</span></div>}</footer> }
function ApprovalDialog({ view, manual, onClose, onApprove, saving }: { view: DailyReportView; manual: DailyReportManualPayload; onClose: () => void; onApprove: () => void; saving: boolean }) {
  const c=view.content; const reconciliation=view.revenueReconciliation; const report=view.report!
  const symphonyFields = ['foodRevenue','beverageRevenue','wineRevenue','liquorRevenue','totalSale','totalDiscount','totalVoid','netSale','totalRevenue'] as const
  return <div className="modal-backdrop final-report-backdrop"><article className="modal report-approval-dialog" role="dialog" aria-modal="true" aria-label="Final Daily Report Review and Approval Preview">
    <button className="close" aria-label="Close approval preview" onClick={onClose}>×</button>
    <header className="approval-report-header"><div><p className="eyebrow">FINAL DAILY REPORT REVIEW / APPROVAL PREVIEW</p><h2>Andalucía</h2><strong>{formatDate(view.serviceDate)}</strong></div><div><StatusBadge status="reviewed" /><small>Prepared by <b>{report.preparedByName}</b> · {new Date(report.preparedAt).toLocaleString()}</small><small>Reviewed by <b>{report.reviewedByName || '—'}</b> · {report.reviewedAt ? new Date(report.reviewedAt).toLocaleString() : '—'}</small></div></header>
    <PreviewSection title="Service Performance"><div className="approval-metric-grid"><Detail label="Total Covers" value={c.servicePerformance.totalCovers} /><Detail label="Adults" value={c.servicePerformance.adults} /><Detail label="Kids" value={c.servicePerformance.kids} /><Detail label="Total Bookings" value={c.servicePerformance.totalBookings} /><Detail label="Arrived Covers" value={c.servicePerformance.arrivedCovers} /><Detail label="No-show Covers" value={c.servicePerformance.noShowCovers} /><Detail label="No-show Rooms" value={<RoomList rooms={c.servicePerformance.noShowRooms} />} /><Detail label="Walk-ins" value={c.servicePerformance.walkIns} /></div></PreviewSection>
    <PreviewSection title="Symphony"><div className="approval-metric-grid symphony-preview">{symphonyFields.map(key => <Detail key={key} label={labelKey(key)} value={displayMoney(manual.symphony[key])} />)}</div>{reconciliation.status === 'verified-with-variance' && <section className="approval-variance prominent"><p className="eyebrow">REVENUE VARIANCE — VERIFIED AGAINST SYMPHONY</p><div><Detail label="Net Sale" value={money(reconciliation.netSale || 0)} /><Detail label="Total Revenue" value={money(reconciliation.totalRevenue || 0)} /><Detail label="Difference" value={money(reconciliation.difference || 0)} /></div><b>✓ Verified by {reconciliation.verifiedByName} · {reconciliation.verifiedAt ? new Date(reconciliation.verifiedAt).toLocaleString() : '—'}</b></section>}</PreviewSection>
    <div className="approval-support-grid"><PreviewSection title="Double Dine"><div className="approval-headline"><span>Total Pax</span><b>{manual.serviceVerification.doubleDinePax ?? 'Not entered'}</b></div>{manual.serviceVerification.details.length > 0 ? <div className="approval-detail-list">{manual.serviceVerification.details.map((row,index) => <span key={`${row.roomNumber}-${index}`}><b>{row.roomNumber || 'No room'} · {row.pax} pax</b>{row.sourceOutlet && ` · ${row.sourceOutlet}`}{row.note && ` · ${row.note}`}</span>)}</div> : <small>No optional details entered.</small>}</PreviewSection><PreviewSection title="Upselling"><div className="approval-metric-grid compact"><Detail label="Total Upsell Revenue" value={money(c.upselling.totalUpsellRevenue)} /><Detail label="Items Sold" value={c.upselling.itemsSold} /><Detail label="Top Item" value={c.upselling.topItem} /><Detail label="Top Seller" value={c.upselling.topSeller} /></div></PreviewSection></div>
    <PreviewSection title="Guest Occasions"><div className="approval-occasion-grid">{c.guestOccasions.categories.filter(category => category.count > 0).map(category => <div key={category.key}><b>{category.label}</b><span>{category.count} · {category.covers} pax</span><RoomList rooms={c.guestOccasions.roomDetails.filter(room => room.category === category.key || room.label.toLowerCase() === category.label.toLowerCase()).map(room => room.roomNumber || 'No room')} /></div>)}{!c.guestOccasions.categories.some(category => category.count > 0) && <small>No guest occasions recorded.</small>}</div></PreviewSection>
    <PreviewSection title="Manager's Operation Summary"><p className="approval-manager-summary">{manual.manager.operationSummary}</p></PreviewSection>
    <footer className="approval-decision"><p><b>Approval creates the immutable authoritative Daily Report snapshot.</b><br />Review every value before continuing. Approval is never automatic.</p><div className="form-actions"><button className="secondary" onClick={onClose}>Back to Report</button><button className="primary approval-action" disabled={saving} onClick={onApprove}>{saving ? 'Approving…' : 'APPROVE DAILY REPORT'}</button></div></footer>
  </article></div>
}

function PreviewSection({ title, children }: { title: string; children: ReactNode }) { return <section className="approval-report-section"><h3>{title}</h3>{children}</section> }

function DailyReadinessGrid({ items }: { items: DailyReportView['readiness'] }) { return <div className="monthly-readiness daily-readiness">{items.map(item => <article className={item.state} key={item.key}><StatusBadge status={item.state} /><div><b>{item.label}</b><small>{item.message}</small>{item.blocking ? <strong>Blocking</strong> : item.verificationRequired ? <strong>Manager verification</strong> : null}</div></article>)}</div> }

function LegacyReport({ mode, onToast, onPeriodLabelChange }: { mode: 'week' | 'month' | 'custom'; onToast: (message: string) => void; onPeriodLabelChange: (label: string) => void }) {
  const range = mode === 'week' ? weekRange(serviceDate()) : mode === 'month' ? monthRange(serviceDate()) : [serviceDate(),serviceDate()] as const; const [start,setStart]=useState(range[0]); const [end,setEnd]=useState(range[1]); const [report,setReport]=useState<OperationalReport|null>(null); const [notes,setNotes]=useState(''); const [error,setError]=useState(''); const valid=isDate(start)&&isDate(end)&&start<=end
  useEffect(() => { const next=mode==='week'?weekRange(serviceDate()):mode==='month'?monthRange(serviceDate()):[start,end] as const; setStart(next[0]);setEnd(next[1]) },[mode])
  useEffect(() => { if(!valid)return; onPeriodLabelChange(`${formatDate(start)}${start===end?'':` – ${formatDate(end)}`}`); void reportingApi.report(mode,start,end).then(next=>{setReport(next);setNotes(next.managerSummary?.managerNotes||'');setError('')}).catch(loadError=>setError(loadError instanceof Error?loadError.message:'Unable to load report.')) },[mode,start,end,valid])
  const save=async()=>{try{const saved=await reportingApi.saveManagerSummary({periodType:mode,startDate:start,endDate:end,managerNotes:notes});setReport(current=>current?{...current,managerSummary:saved}:current);onToast('Manager summary saved.')}catch(saveError){onToast(saveError instanceof Error?saveError.message:'Unable to save manager summary.')}}
  return <><section className="report-controls panel"><div className="report-dates"><label>Start Date<input type="date" value={start} disabled={mode!=='custom'} onChange={event=>setStart(event.target.value)} /></label><span>to</span><label>End Date<input type="date" value={end} disabled={mode!=='custom'} min={start} onChange={event=>setEnd(event.target.value)} /></label></div><button className="secondary" onClick={()=>window.print()}>Print Report</button></section>{error&&<div className="panel inline-state error-state">{error}</div>}{report&&<><ReportSection id="legacy-bookings" eyebrow="RESTAURANT PERFORMANCE" title="Booking Performance"><div className="daily-kpis"><Stat label="Total Covers" value={report.bookings.totalCovers}/><Stat label="Adults" value={report.bookings.totalAdults}/><Stat label="Kids" value={report.bookings.totalKids}/><Stat label="No-show Covers" value={report.bookings.noShowCovers}/></div><ReportTable headers={mode==='month'?['Week','Covers','Adults','Kids','No-shows']:['Date','Covers','Adults','Kids','No-shows']}>{(mode==='month'?report.bookings.byWeek:report.bookings.byDate).map((item:any)=><tr key={item.weekStart||item.date}><td>{item.label||formatDate(item.date)}</td><td>{item.totalCovers}</td><td>{item.totalAdults}</td><td>{item.totalKids}</td><td>{item.noShowCovers}</td></tr>)}</ReportTable></ReportSection><div className="report-support-grid"><ReportSection id="legacy-occasions" eyebrow="GUEST EXPERIENCE" title="Guest Occasions"><Stat label="Total Occasions" value={report.occasions.total}/><div className="breakdown-chips">{report.occasions.byCategory.map(item=><span key={item.key}>{item.label}<b>{item.count}</b></span>)}</div></ReportSection><ReportSection id="legacy-commercial" eyebrow="COMMERCIAL" title="Chargeable Items & Revenue"><div className="compact-metrics"><Stat label="Realized Revenue" value={money(report.chargeables.realizedRevenue)}/><Stat label="Top Item" value={report.chargeables.topItem?.item||'—'}/><Stat label="Top Waiter" value={report.chargeables.topWaiter?.waiter||'—'}/></div></ReportSection></div><ReportSection id="legacy-maintenance" eyebrow="OPERATIONS" title="Maintenance"><Stat label="Completed" value={mode==='custom'?report.maintenance.completedDuringPeriod:report.maintenance.completedToday}/></ReportSection><ReportSection id="legacy-manager" eyebrow="LEGACY PERIOD COMMENTARY" title="Manager Period Commentary"><textarea rows={7} value={notes} onChange={event=>setNotes(event.target.value)} /><div className="manager-summary-actions"><small>Preserved legacy Weekly / Monthly / Custom commentary</small><button className="primary" onClick={()=>void save()}>Save Manager Summary</button></div></ReportSection></>}</>
}

function StatusBadge({status}:{status:string}){return <span className={`daily-status ${status.toLowerCase()}`}>{status.replaceAll('-',' ').toUpperCase()}</span>}
function Stat({label,value,attention=false}:{label:string;value:ReactNode;attention?:boolean}){return <article className={attention?'report-stat attention':'report-stat'}><span>{label}</span><strong>{value}</strong></article>}
function Detail({label,value}:{label:string;value:ReactNode}){return <div><span>{label}</span><b>{value}</b></div>}
function RoomList({rooms,limit=5}:{rooms:string[];limit?:number}){const [expanded,setExpanded]=useState(false);const values=rooms.filter(Boolean);const hidden=Math.max(0,values.length-limit);const shown=expanded?values:values.slice(0,limit);const complete=values.length?values.join(' · '):'—';return <span className="report-room-list"><span className="report-room-screen">{shown.length?shown.join(' · '):'—'}</span>{hidden>0&&<button type="button" className="report-room-more" aria-expanded={expanded} onClick={()=>setExpanded(value=>!value)}>{expanded?'Show less':`+${hidden} more`}</button>}<span className="report-room-print">{complete}</span></span>}
function ReportSection({id,eyebrow,title,children}:{id?:string;eyebrow:string;title:string;children:ReactNode}){return <section className="panel report-section" id={id}><div className="report-section-title"><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div>{children}</section>}
function ReportTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="report-table-wrap" role="region" aria-label={`${headers[0]} report table`} tabIndex={0}><table className="report-table"><thead><tr>{headers.map(header=><th scope="col" key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Empty(){return <div className="report-empty">No persisted records for this service date.</div>}
