import { useEffect, useMemo, useState } from 'react'
import { staffApi } from './api'
import type { LeaveClassification, Staff, StaffLeaveRecord } from './domain'
import { monthRange, serviceDate } from './service-date'

type Period = 'month' | 'year' | 'custom'
const leaveLabels: Record<LeaveClassification, string> = { annualLeave: 'Annual Leave', off: 'Off Day', publicHoliday: 'Public Holiday', sickLeave: 'Sick Leave' }
const displayDate = (value: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00Z`))
const standardRange = (period: Period) => period === 'month' ? monthRange(serviceDate()) : [`${serviceDate().slice(0, 4)}-01-01`, `${serviceDate().slice(0, 4)}-12-31`] as [string, string]

function PeriodControls({ period, onPeriod, start, end, onStart, onEnd }: { period: Period; onPeriod: (value: Period) => void; start: string; end: string; onStart: (value: string) => void; onEnd: (value: string) => void }) {
  return <div className="leave-period-controls"><label>Period<select value={period} onChange={event => onPeriod(event.target.value as Period)}><option value="month">This Month</option><option value="year">This Year</option><option value="custom">Custom Period</option></select></label>{period === 'custom' && <><label>From<input type="date" value={start} onChange={event => onStart(event.target.value)} /></label><label>To<input type="date" value={end} onChange={event => onEnd(event.target.value)} /></label></>}</div>
}

const useLeaveRecords = (period: Period, customStart: string, customEnd: string, staffId?: string) => {
  const [records, setRecords] = useState<StaffLeaveRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const range = period === 'custom' ? [customStart, customEnd] as [string, string] : standardRange(period)
  useEffect(() => { let current = true; setLoading(true); setError(''); void staffApi.leaveRecords(range[0], range[1], staffId).then(value => { if (current) setRecords(value) }).catch(loadError => { if (current) setError(loadError instanceof Error ? loadError.message : 'Unable to load leave records.') }).finally(() => { if (current) setLoading(false) }); return () => { current = false } }, [range[0], range[1], staffId])
  return { records, loading, error }
}

export function StaffLeaveAvailability({ staff, onViewFull }: { staff: Staff; onViewFull: () => void }) {
  const today = serviceDate(); const [period, setPeriod] = useState<Period>('year'); const [start, setStart] = useState(`${today.slice(0, 4)}-01-01`); const [end, setEnd] = useState(`${today.slice(0, 4)}-12-31`)
  const { records, loading, error } = useLeaveRecords(period, start, end, staff.id)
  const entries = records.flatMap(record => record.entries)
  const totals = { annualLeave: entries.filter(day => day.classification === 'annualLeave').length, off: entries.filter(day => day.classification === 'off').length, publicHoliday: entries.filter(day => day.classification === 'publicHoliday').length, sickLeave: entries.filter(day => day.classification === 'sickLeave').length }
  return <section className="staff-leave-profile"><div className="staff-leave-heading"><div><p className="eyebrow">LEAVE &amp; AVAILABILITY</p><small>Derived automatically from Duty Roster.</small></div><PeriodControls period={period} onPeriod={setPeriod} start={start} end={end} onStart={setStart} onEnd={setEnd} /></div>{loading ? <p className="leave-state">Calculating roster availability…</p> : error ? <p className="save-error">{error}</p> : <div className="leave-summary-cards"><article className="annual"><span>Annual Leave</span><b>{totals.annualLeave} days</b></article><article className="off"><span>Off Days</span><b>{totals.off} days</b></article><article className="holiday"><span>Public Holidays</span><b>{totals.publicHoliday} days</b></article><article className="sick"><span>Sick Leave</span><b>{totals.sickLeave} days</b></article></div>}<button className="link leave-history-link" onClick={onViewFull}>View Full Leave History →</button></section>
}

export function LeaveRecordsPanel({ staff, initialStaffId }: { staff: Staff[]; initialStaffId?: string }) {
  const today = serviceDate(); const [period, setPeriod] = useState<Period>('year'); const [start, setStart] = useState(`${today.slice(0, 4)}-01-01`); const [end, setEnd] = useState(`${today.slice(0, 4)}-12-31`); const [query, setQuery] = useState(''); const [staffId, setStaffId] = useState(initialStaffId || 'all'); const [leaveType, setLeaveType] = useState<'all' | LeaveClassification>('all'); const [timing, setTiming] = useState<'all' | 'current' | 'upcoming' | 'historical'>('all'); const [selected, setSelected] = useState<StaffLeaveRecord | null>(null)
  useEffect(() => { if (initialStaffId) setStaffId(initialStaffId) }, [initialStaffId])
  const { records, loading, error } = useLeaveRecords(period, start, end, staffId === 'all' ? undefined : staffId)
  const visible = useMemo(() => records.filter(record => (leaveType === 'all' || record.leaveType === leaveType) && `${record.staffName} ${record.staffNumber}`.toLowerCase().includes(query.toLowerCase()) && (timing === 'all' || timing === 'current' && record.fromDate <= today && record.toDate >= today || timing === 'upcoming' && record.fromDate > today || timing === 'historical' && record.toDate < today)), [records, leaveType, query, timing, today])
  const person = (id: string) => staff.find(item => item.id === id)
  return <section className="panel leave-records-panel">
    <div className="leave-records-header"><div><p className="eyebrow">LEAVE HISTORY</p><h2>Confirmed source evidence</h2><p>Read-only periods and source days derived from Duty Roster.</p></div></div>
    <div className="leave-record-filters"><input aria-label="Search leave history" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search staff name / Employee ID" /><select aria-label="Filter leave history by staff" value={staffId} onChange={event => setStaffId(event.target.value)}><option value="all">All staff</option>{staff.map(item => <option key={item.id} value={item.id}>{item.name} · {item.number}</option>)}</select><select aria-label="Filter by leave type" value={leaveType} onChange={event => setLeaveType(event.target.value as typeof leaveType)}><option value="all">All leave types</option>{Object.entries(leaveLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filter by leave timing" value={timing} onChange={event => setTiming(event.target.value as typeof timing)}><option value="all">All periods</option><option value="current">Current</option><option value="upcoming">Upcoming</option><option value="historical">Historical</option></select><PeriodControls period={period} onPeriod={setPeriod} start={start} end={end} onStart={setStart} onEnd={setEnd} /></div>
    {loading ? <p className="leave-state">Loading leave history…</p> : error ? <p className="save-error">{error}</p> : <>
      <div className="leave-table-wrap" tabIndex={0}><table className="leave-records-table"><thead><tr><th>Staff</th><th>Designation</th><th>Type / Code</th><th>Start</th><th>End</th><th>Entitlement Days</th><th>Calendar Span</th><th>Source</th><th>Actions</th></tr></thead><tbody>{visible.map(record => <tr key={record.id}><td><b>{record.staffName}</b><small>{record.staffNumber}</small></td><td>{person(record.staffId)?.position || '—'}</td><td><span className={`leave-type-chip ${record.leaveType}`}>{record.entries[0]?.dutyCode || leaveLabels[record.leaveType]}</span><small>{leaveLabels[record.leaveType]}</small></td><td>{displayDate(record.fromDate)}</td><td>{displayDate(record.toDate)}</td><td>{record.leaveType === 'publicHoliday' ? record.holidays : record.leaveType === 'off' ? record.offDays : record.leaveDays}</td><td><b>{record.totalDays}</b></td><td>Duty Roster</td><td><button className="link" onClick={() => setSelected(record)}>View Source Days</button></td></tr>)}</tbody></table></div>
      <div className="leave-mobile-cards">{visible.map(record => <article key={record.id}><header><div><b>{record.staffName}</b><small>{person(record.staffId)?.position || '—'} · {record.staffNumber}</small></div><span className={`leave-type-chip ${record.leaveType}`}>{record.entries[0]?.dutyCode || leaveLabels[record.leaveType]}</span></header><h3>{leaveLabels[record.leaveType]}</h3><p>{displayDate(record.fromDate)} – {displayDate(record.toDate)}</p><dl><div><dt>Entitlement</dt><dd>{record.leaveType === 'publicHoliday' ? record.holidays : record.leaveType === 'off' ? record.offDays : record.leaveDays}</dd></div><div><dt>Calendar</dt><dd>{record.totalDays}</dd></div><div><dt>Source</dt><dd>Roster</dd></div><div><dt>Days</dt><dd>{record.entries.length}</dd></div></dl><button className="secondary" onClick={() => setSelected(record)}>View Source Days</button></article>)}</div>
      {visible.length === 0 && <p className="inline-empty">No confirmed Duty Roster evidence matches these filters.</p>}
    </>}
    {selected && <LeaveRecordDrawer record={selected} designation={person(selected.staffId)?.position} onClose={() => setSelected(null)} />}
  </section>
}

function LeaveRecordDrawer({ record, designation, onClose }: { record: StaffLeaveRecord; designation?: string; onClose: () => void }) {
  return <div className="staff-profile-overlay"><aside className="staff-profile-drawer leave-record-drawer" role="dialog" aria-modal="true" aria-label={`Leave history for ${record.staffName}`}><button className="close" aria-label="Close leave history" onClick={onClose}>×</button><header><p className="eyebrow">LEAVE HISTORY EVIDENCE</p><h2>{record.staffName}</h2><span>{record.staffNumber} · {designation || '—'}</span></header><section><dl className="staff-profile-grid"><div><dt>Type / code</dt><dd>{record.entries[0]?.dutyCode} · {leaveLabels[record.leaveType]}</dd></div><div><dt>Confirmation source</dt><dd>Duty Roster</dd></div><div><dt>Start</dt><dd>{displayDate(record.fromDate)}</dd></div><div><dt>End</dt><dd>{displayDate(record.toDate)}</dd></div><div><dt>Entitlement days</dt><dd>{record.leaveType === 'publicHoliday' ? record.holidays : record.leaveType === 'off' ? record.offDays : record.leaveDays}</dd></div><div><dt>Calendar span</dt><dd>{record.totalDays}</dd></div></dl></section><section><p className="eyebrow">SOURCE DAYS</p><div className="leave-daily-list">{record.entries.map(day => <div key={day.date}><time>{displayDate(day.date)}</time><b>{day.dutyCode}</b><span>{day.dutyLabel}</span></div>)}</div></section></aside></div>
}
