import { useEffect, useMemo, useRef, useState } from 'react'
import { trainingApi } from './api'
import type { Staff, TrainingCompletionInput, TrainingEligibilityState, TrainingImportPreview, TrainingPerformance, TrainingSession, TrainingSessionDetail, TrainingStaffEvidence } from './domain'
import { addCalendarMonths, calendarDates, monthRange, serviceDate } from './service-date'
import { TrainingForm, TrainingImportReview, type TrainingConfiguration } from './training'
import { trainingImportResultMessage } from './training-import-review'

type Props = { staff: Staff[]; configuration: TrainingConfiguration; onToast: (message: string) => void }
type View = 'calendar' | 'list'

const dateLabel = (date: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`))
const monthLabel = (month: string) => new Intl.DateTimeFormat('en-GB', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${month}-01T00:00:00Z`))
const timeLabel = (session: TrainingSession) => `${session.startTime || session.time}${session.endTime ? `–${session.endTime}` : ''}`
const statusLabel = (session: TrainingSession) => ({ scheduled: 'Scheduled', awaiting_confirmation: 'Awaiting Confirmation', completed: 'Completed', cancelled: 'Cancelled' }[session.operationalStatus || 'scheduled'])
const categoryLabel = (configuration: TrainingConfiguration, value: string) => configuration.categories.find(item => item.value === value)?.label || value
const workflowColor = (configuration: TrainingConfiguration, state?: string) => configuration.workflow?.find(item => item.state === (state || 'scheduled'))?.color
const sourceLabel = (session: TrainingSession) => session.source === 'hr_calendar' ? 'HR File Import' : session.source === 'sharepoint' ? 'Future SharePoint Sync' : 'Manual'
const minutesBetween = (session: TrainingSession) => { const [sh, sm] = (session.startTime || session.time).split(':').map(Number); const [eh, em] = (session.endTime || session.time).split(':').map(Number); return Math.max(1, (eh * 60 + em) - (sh * 60 + sm)) }

export function TrainingR2Page({ staff, configuration, onToast }: Props) {
  const today = serviceDate()
  const [month, setMonth] = useState(today.slice(0, 7))
  const [view, setView] = useState<View>('calendar')
  const [sessions, setSessions] = useState<TrainingSession[]>([])
  const [performance, setPerformance] = useState<TrainingPerformance | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [category, setCategory] = useState('all')
  const [editing, setEditing] = useState<TrainingSession | 'new' | null>(null)
  const [detailId, setDetailId] = useState<string | null>(null)
  const [preview, setPreview] = useState<TrainingImportPreview | null>(null)
  const [importing, setImporting] = useState(false)
  const fileInput = useRef<HTMLInputElement>(null)

  const load = async () => {
    setLoading(true); setError('')
    try { const [records, metrics] = await Promise.all([trainingApi.list(), trainingApi.performance(month)]); setSessions(records); setPerformance(metrics) }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load Training.') }
    finally { setLoading(false) }
  }
  useEffect(() => { void load() }, [month])

  const active = useMemo(() => sessions.filter(item => item.active && item.date.startsWith(month)).sort((a, b) => a.date.localeCompare(b.date) || (a.startTime || a.time).localeCompare(b.startTime || b.time)), [sessions, month])
  const filtered = useMemo(() => active.filter(item => `${item.title} ${item.trainer} ${item.location || ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || item.operationalStatus === status) && (category === 'all' || item.category === category)), [active, query, status, category])
  const next = sessions.filter(item => item.active && item.date >= today && item.operationalStatus === 'scheduled').sort((a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time))[0]

  const save = async (record: TrainingSession) => { await (sessions.some(item => item.id === record.id) ? trainingApi.update(record) : trainingApi.create(record)); setEditing(null); onToast('Training session saved.'); await load() }
  const upload = async (file?: File) => { if (!file) return; setImporting(true); setError(''); try { setPreview(await trainingApi.previewImport(file)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to parse the HR calendar.') } finally { setImporting(false); if (fileInput.current) fileInput.current.value = '' } }

  return <div className="training-r2">
    <section className="training-r2-toolbar">
      <div><p>Plan local training, confirm delivery and monitor staff coverage.</p><div className="view-switch" role="group" aria-label="Training view"><button className={view === 'calendar' ? 'selected' : ''} onClick={() => setView('calendar')}>Calendar</button><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}>List</button></div></div>
      <div className="training-r2-actions"><input ref={fileInput} type="file" hidden accept=".xlsx,.xls,.csv,.pdf,.png,.jpg,.jpeg,.webp" onChange={event => void upload(event.target.files?.[0])} /><button className="secondary" disabled={importing} onClick={() => fileInput.current?.click()}>{importing ? 'Parsing…' : '⇧ Import HR Calendar'}</button><button className="primary" onClick={() => setEditing('new')}>＋ Add Training</button></div>
    </section>
    <section className="training-r2-period"><button className="secondary" aria-label="Previous month" onClick={() => setMonth(addCalendarMonths(`${month}-01`, -1).slice(0, 7))}>←</button><strong>{monthLabel(month)}</strong><button className="secondary" aria-label="Next month" onClick={() => setMonth(addCalendarMonths(`${month}-01`, 1).slice(0, 7))}>→</button></section>
    {error && <div className="inline-state error-state"><p>{error}</p><button className="secondary" onClick={() => void load()}>Try again</button></div>}
    {!error && (loading || !performance) ? <div className="inline-state">Loading Training performance…</div> : !error && performance ? <>
      <TrainingKpis performance={performance} />
      <section className={`training-target-strip ${performance.targetAchieved ? 'achieved' : ''}`}><div><b>{performance.targetAchieved ? 'Monthly target achieved' : `${performance.remainingHours} hrs remaining`}</b><span>{performance.trainingHours} of {performance.target.monthlyHours} credited hours · {performance.staffCovered} of {performance.eligibleHeadcount} staff covered</span></div><div className="training-target-track"><i style={{ width: `${Math.min(100, performance.target.monthlyMinutes ? performance.creditedMinutes / performance.target.monthlyMinutes * 100 : 0)}%` }} /></div></section>
      {performance.requiresReview > 0 && <button className="training-review-alert" onClick={() => { setStatus('awaiting_confirmation'); setView('list') }}><b>{performance.requiresReview} session{performance.requiresReview === 1 ? '' : 's'} awaiting confirmation</b><span>Review past sessions before they count toward Training performance.</span></button>}
      <section className="panel training-next"><div><p className="eyebrow">NEXT TRAINING</p>{next ? <><h2>{next.title}</h2><span>{dateLabel(next.date)} · {timeLabel(next)} · {next.trainer}</span></> : <><h2>No upcoming session</h2><span>Add a local session or import the next HR calendar.</span></>}</div>{next && <button className="secondary" onClick={() => setDetailId(next.id)}>View details</button>}</section>
      {view === 'calendar' ? <TrainingCalendar month={month} sessions={filtered} configuration={configuration} onView={setDetailId} /> : <TrainingList sessions={filtered} configuration={configuration} query={query} status={status} category={category} onQuery={setQuery} onStatus={setStatus} onCategory={setCategory} onView={setDetailId} onEdit={setEditing} />}
      <CoveragePanel performance={performance} />
    </> : null}
    {view === 'calendar' && <TrainingFilters configuration={configuration} query={query} status={status} category={category} onQuery={setQuery} onStatus={setStatus} onCategory={setCategory} />}
    {editing && <TrainingForm session={editing === 'new' ? undefined : editing} configuration={configuration} sessions={sessions} staff={staff} onClose={() => setEditing(null)} onSave={save} />}
    {detailId && <TrainingDetailDrawer id={detailId} configuration={configuration} onClose={() => setDetailId(null)} onEdit={session => { setDetailId(null); setEditing(session) }} onChanged={load} />}
    {preview && <TrainingImportReview preview={preview} onClose={() => setPreview(null)} onUploadNew={() => { setPreview(null); setTimeout(() => fileInput.current?.click(), 0) }} onImported={async result => { setPreview(null); onToast(trainingImportResultMessage(result)); await load() }} />}
  </div>
}

function TrainingKpis({ performance: p }: { performance: TrainingPerformance }) {
  const metrics = [
    ['Sessions Scheduled', p.sessionsScheduled], ['Completed', p.sessionsCompleted], ['MTD Training Hours', `${p.trainingHours} / ${p.target.monthlyHours} hrs`],
    ['Hours / Head', `${p.hoursPerHead} / ${p.target.perHeadHours} hrs`], ['Staff Covered', `${p.staffCovered} / ${p.eligibleHeadcount}`], ['Remaining to Target', p.targetAchieved ? 'Achieved' : `${p.remainingHours} hrs`]
  ]
  return <section className="training-r2-kpis">{metrics.map(([label, value]) => <article className="panel" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
}

function TrainingFilters({ configuration, query, status, category, onQuery, onStatus, onCategory }: { configuration: TrainingConfiguration; query: string; status: string; category: string; onQuery: (v: string) => void; onStatus: (v: string) => void; onCategory: (v: string) => void }) {
  return <section className="training-r2-filters"><input aria-label="Search Training" placeholder="Search topic, trainer or location" value={query} onChange={event => onQuery(event.target.value)} /><select aria-label="Filter operational Training status" value={status} onChange={event => onStatus(event.target.value)}><option value="all">All operational statuses</option><option value="scheduled">Scheduled</option><option value="awaiting_confirmation">Awaiting Confirmation</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><select aria-label="Filter Training category" value={category} onChange={event => onCategory(event.target.value)}><option value="all">All categories</option>{configuration.categories.filter(item => item.active || item.value === category).map(item => <option key={item.id} value={item.value}>{item.label}</option>)}</select></section>
}

function TrainingCalendar({ month, sessions, configuration, onView }: { month: string; sessions: TrainingSession[]; configuration: TrainingConfiguration; onView: (id: string) => void }) {
  const [start, end] = monthRange(`${month}-01`); const dates = calendarDates(start, end); const blanks = (new Date(`${start}T00:00:00Z`).getUTCDay() + 6) % 7
  return <section className="panel training-calendar training-r2-calendar"><div className="training-weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day => <b key={day}>{day}</b>)}</div><div className="training-calendar-grid">{Array.from({ length: blanks }, (_, i) => <div className="calendar-blank" key={i} />)}{dates.map(date => <article key={date} className={date === serviceDate() ? 'today' : ''}><time>{Number(date.slice(-2))}</time><div>{sessions.filter(item => item.date === date).map(item => <button className={`training-event ${item.operationalStatus}`} style={{ borderLeftColor: workflowColor(configuration, item.operationalStatus) }} key={item.id} onClick={() => onView(item.id)} title={`${item.title} — ${statusLabel(item)}`}><b>{item.title}</b><span>{timeLabel(item)}</span><small>{item.trainer}</small><em style={{ color: workflowColor(configuration, item.operationalStatus) }}>{statusLabel(item)}</em></button>)}</div></article>)}</div></section>
}

function TrainingList({ sessions, configuration, query, status, category, onQuery, onStatus, onCategory, onView, onEdit }: { sessions: TrainingSession[]; configuration: TrainingConfiguration; query: string; status: string; category: string; onQuery: (v: string) => void; onStatus: (v: string) => void; onCategory: (v: string) => void; onView: (id: string) => void; onEdit: (s: TrainingSession) => void }) {
  return <section className="panel training-r2-list"><header><div><p className="eyebrow">LOCAL TRAINING</p><h2>Training Sessions</h2></div><TrainingFilters configuration={configuration} query={query} status={status} category={category} onQuery={onQuery} onStatus={onStatus} onCategory={onCategory} /></header><div className="training-r2-table"><table><thead><tr><th>Date</th><th>Topic</th><th>Time</th><th>Trainer</th><th>Category</th><th>Status</th><th>Source</th><th>Actions</th></tr></thead><tbody>{sessions.map(item => <tr key={item.id}><td>{dateLabel(item.date)}</td><td><b>{item.title}</b></td><td>{timeLabel(item)}</td><td>{item.trainer}</td><td>{categoryLabel(configuration, item.category)}</td><td><span className={`training-status ${item.operationalStatus}`}>{statusLabel(item)}</span></td><td><small>{sourceLabel(item)}</small></td><td className="row-actions"><button className="link" onClick={() => onView(item.id)}>View</button>{item.operationalStatus !== 'completed' && <button className="link" onClick={() => onEdit(item)}>Edit</button>}</td></tr>)}</tbody></table></div><div className="training-r2-cards">{sessions.map(item => <article key={item.id}><header><div><b>{item.title}</b><small>{dateLabel(item.date)} · {timeLabel(item)}</small></div><span className={`training-status ${item.operationalStatus}`}>{statusLabel(item)}</span></header><dl><div><dt>Trainer</dt><dd>{item.trainer}</dd></div><div><dt>Category</dt><dd>{categoryLabel(configuration, item.category)}</dd></div><div><dt>Location</dt><dd>{item.location || 'Andalucía'}</dd></div><div><dt>Source</dt><dd>{sourceLabel(item)}</dd></div></dl><footer><button className="secondary" onClick={() => onView(item.id)}>View details</button>{item.operationalStatus !== 'completed' && <button className="link" onClick={() => onEdit(item)}>Edit</button>}</footer></article>)}</div>{!sessions.length && <p className="inline-empty">No Training sessions match this view.</p>}</section>
}

function CoveragePanel({ performance }: { performance: TrainingPerformance }) {
  const [open, setOpen] = useState(false)
  return <section className="panel training-coverage"><header><div><p className="eyebrow">STAFF COVERAGE</p><h2>Staff Training Coverage</h2><span>{performance.staffCovered} of {performance.eligibleHeadcount} staff have confirmed credited Training this month.</span></div><button className="secondary" onClick={() => setOpen(value => !value)} aria-expanded={open}>{open ? 'Hide coverage' : 'View coverage'}</button></header>{open && <div className="training-coverage-grid">{performance.staffCoverage.map(person => <article key={person.staffId} className={person.minimumAchieved ? 'achieved' : ''}><header><div><b>{person.staffName}</b><small>{person.staffNumber} · {person.designation}</small></div><span>{person.minimumAchieved ? 'Target met' : `${person.remainingMinutes} min left`}</span></header><div><b>{person.creditedHours} hrs</b><small>{person.sessionsAttended} confirmed session{person.sessionsAttended === 1 ? '' : 's'} · target {person.targetMinutes / 60} hrs</small></div></article>)}</div>}</section>
}

function TrainingDetailDrawer({ id, configuration, onClose, onEdit, onChanged }: { id: string; configuration: TrainingConfiguration; onClose: () => void; onEdit: (session: TrainingSession) => void; onChanged: () => Promise<void> }) {
  const [detail, setDetail] = useState<TrainingSessionDetail | null>(null); const [error, setError] = useState(''); const [confirming, setConfirming] = useState(false)
  useEffect(() => { void trainingApi.detail(id).then(setDetail).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load Training details.')) }, [id])
  return <div className="staff-profile-overlay"><aside className="staff-profile-drawer training-r2-drawer" role="dialog" aria-modal="true" aria-label="Training details"><button className="close" aria-label="Close Training details" onClick={onClose}>×</button>{error && <p className="save-error">{error}</p>}{!detail && !error ? <div className="inline-state">Loading Training details…</div> : detail ? <><header><p className="eyebrow">{detail.sourceLabel}</p><h2>{detail.session.title}</h2><span className={`training-status ${detail.operationalStatus}`}>{statusLabel(detail.session)}</span></header><section className="training-session-section"><h3>Session</h3><dl className="training-detail-grid"><div><dt>Date</dt><dd>{dateLabel(detail.session.date)}</dd></div><div><dt>Time</dt><dd>{timeLabel(detail.session)}</dd></div><div><dt>Trainer</dt><dd>{detail.session.trainer}</dd></div><div><dt>Location</dt><dd>{detail.session.location || 'Andalucía'}</dd></div><div><dt>Category</dt><dd>{categoryLabel(configuration, detail.session.category)}</dd></div><div><dt>Source</dt><dd>{detail.sourceLabel}</dd></div></dl>{detail.session.description && <p>{detail.session.description}</p>}</section>{detail.completion && <section><h3>Confirmed performance</h3><dl className="training-detail-grid"><div><dt>Actual duration</dt><dd>{detail.completion.actualDurationMinutes} min</dd></div><div><dt>Credit / participant</dt><dd>{detail.completion.creditedMinutesPerParticipant} min</dd></div><div><dt>Participants</dt><dd>{detail.completion.participantCount} / {detail.completion.eligibleStaff}</dd></div><div><dt>Coverage</dt><dd>{detail.coveragePercent ?? 0}%</dd></div><div><dt>Training hours</dt><dd>{detail.sessionTrainingHours}</dd></div><div><dt>Confirmed by</dt><dd>{detail.completion.confirmedBy}</dd></div></dl><small>Confirmed {new Date(detail.completion.confirmedAt).toLocaleString('en-GB')}</small></section>}<section className="training-eligibility-section"><h3>{detail.completion ? 'Staff evidence' : 'Eligibility preview'}</h3><div className="training-evidence-list">{detail.staff.map(person => <div key={person.staffId}><span><b>{person.staffName}</b><small>{person.staffNumber} · {person.dutyLabel || 'No roster duty'}</small></span><em>{person.participationState === 'participated' ? `${person.creditedMinutes} min credited` : eligibilityLabel(person)}</em></div>)}</div></section><footer>{detail.operationalStatus !== 'completed' && detail.operationalStatus !== 'cancelled' && <button className="secondary" onClick={() => onEdit(detail.session)}>Edit</button>}{detail.operationalStatus === 'awaiting_confirmation' && !detail.completion && <button className="primary" onClick={() => setConfirming(true)}>Confirm Training</button>}</footer>{confirming && <TrainingConfirmation detail={detail} onClose={() => setConfirming(false)} onConfirmed={async value => { setDetail(value); setConfirming(false); await onChanged() }} />}</> : null}</aside></div>
}

const eligibilityLabel = (person: TrainingStaffEvidence) => person.eligibilityState === 'eligible' ? 'Eligible · not confirmed' : person.eligibilityState === 'excluded_off' ? 'OFF · excluded' : person.eligibilityState === 'excluded_annual_leave' ? 'Annual leave · excluded' : 'Manager review required'

function TrainingConfirmation({ detail, onClose, onConfirmed }: { detail: TrainingSessionDetail; onClose: () => void; onConfirmed: (detail: TrainingSessionDetail) => Promise<void> }) {
  const [duration, setDuration] = useState(minutesBetween(detail.session)); const [staff, setStaff] = useState(detail.staff); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const update = (staffId: string, changes: Partial<TrainingStaffEvidence>) => setStaff(current => current.map(item => item.staffId === staffId ? { ...item, ...changes } : item))
  const submit = async () => { setSaving(true); setError(''); try { const input: TrainingCompletionInput = { actualDurationMinutes: duration, staff: staff.map(item => ({ staffId: item.staffId, eligibilityState: item.eligibilityState, participationState: item.eligibilityState === 'eligible' ? item.participationState : 'not_applicable', evidenceNote: item.evidenceNote })) }; await onConfirmed(await trainingApi.confirm(detail.session.id, input)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to confirm Training.') } finally { setSaving(false) } }
  return <div className="modal-backdrop training-confirm-backdrop"><section className="modal training-confirm-modal" role="dialog" aria-modal="true" aria-label="Confirm Training completion"><button className="close" aria-label="Close confirmation" onClick={onClose}>×</button><p className="eyebrow">COMPLETION EVIDENCE</p><h2>Confirm Training</h2><p>Confirm actual delivery and each staff member’s eligibility. Only confirmed participants receive credit, capped at {Math.min(duration, 30)} minutes each.</p><label className="training-duration">Actual duration (minutes)<input type="number" min="1" max="720" value={duration} onChange={event => setDuration(Number(event.target.value))} /></label><div className="training-confirm-list">{staff.map(person => <article key={person.staffId} className={person.eligibilityState}><header><span><b>{person.staffName}</b><small>{person.staffNumber} · {person.dutyLabel || 'No roster duty'}</small></span><em>{person.recommendedEligibility === 'requires_review' ? 'Review required' : eligibilityLabel(person)}</em></header>{person.recommendedEligibility === 'requires_review' && <label>Eligibility<select value={person.eligibilityState} onChange={event => { const eligibilityState = event.target.value as TrainingEligibilityState; update(person.staffId, { eligibilityState, participationState: eligibilityState === 'eligible' ? 'did_not_participate' : 'not_applicable' }) }}><option value="requires_review">Select decision</option><option value="eligible">Eligible to participate</option><option value="excluded_off">Exclude — OFF</option><option value="excluded_annual_leave">Exclude — Annual Leave</option></select></label>}{person.eligibilityState === 'eligible' && <label className="training-participation"><input type="checkbox" checked={person.participationState === 'participated'} onChange={event => update(person.staffId, { participationState: event.target.checked ? 'participated' : 'did_not_participate' })} /> Participated</label>}</article>)}</div>{error && <p className="save-error">{error}</p>}<div className="form-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving || staff.some(item => item.eligibilityState === 'requires_review')} onClick={() => void submit()}>{saving ? 'Confirming…' : 'Confirm completion'}</button></div></section></div>
}
