import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { wineSpiritsApi } from './api'
import type { ConfigOption, Staff, WineSpiritCalculation, WineSpiritSale, WineSpiritSaleInput, WineSpiritSaleStatus } from './domain'
import { serviceDate } from './service-date'
import './wine-spirits.css'

const money = (value: string | number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value || 0))
const statuses: Array<{ value: WineSpiritSaleStatus; label: string }> = [{ value: 'pending', label: 'Pending' }, { value: 'charged', label: 'Charged / Realized' }, { value: 'cancelled', label: 'Cancelled' }, { value: 'void', label: 'Void' }]
const monthRange = (month: string) => ({ start: `${month}-01`, end: `${month}-${String(new Date(Date.UTC(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0)).getUTCDate()).padStart(2, '0')}` })
const toInput = (sale: WineSpiritSale): WineSpiritSaleInput => ({ id: sale.id, serviceDate: sale.serviceDate, checkInvoiceNumber: sale.checkInvoiceNumber, itemName: sale.itemName, roomNumber: sale.roomNumber, tableNumber: sale.tableNumber, waiterId: sale.waiterId, grossUnitPrice: sale.grossUnitPrice, quantity: sale.quantity, status: sale.status, notes: sale.notes })
const statusLabel = (value: WineSpiritSaleStatus) => statuses.find(item => item.value === value)?.label || value

export function WineSpiritsPage({ staff, tables, onToast }: { staff: Staff[]; tables: ConfigOption[]; onToast: (message: string) => void }) {
  const [month, setMonth] = useState(serviceDate().slice(0, 7))
  const [records, setRecords] = useState<WineSpiritSale[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const [waiter, setWaiter] = useState('all')
  const [status, setStatus] = useState<'all' | WineSpiritSaleStatus>('all')
  const [showArchived, setShowArchived] = useState(false)
  const [editing, setEditing] = useState<WineSpiritSale | 'new' | null>(null)
  const [viewing, setViewing] = useState<WineSpiritSale | null>(null)
  const load = async () => { setLoading(true); setError(''); try { const range = monthRange(month); setRecords(await wineSpiritsApi.list(range.start, range.end)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Wine/Spirits sales could not be loaded.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [month])
  const visible = useMemo(() => records.filter(record => {
    const search = `${record.checkInvoiceNumber} ${record.roomNumber} ${record.tableNumber} ${record.itemName} ${record.waiter.name} ${record.waiter.number}`.toLowerCase()
    return (showArchived || !record.archived) && (waiter === 'all' || record.waiterId === waiter) && (status === 'all' || record.status === status) && search.includes(query.toLowerCase())
  }), [records, query, waiter, status, showArchived])
  const saved = (sale: WineSpiritSale) => { setRecords(current => current.some(item => item.id === sale.id) ? current.map(item => item.id === sale.id ? sale : item) : [sale, ...current]); setViewing(current => current?.id === sale.id ? sale : current) }
  const archive = async (sale: WineSpiritSale) => { if (!window.confirm(`${sale.status === 'charged' ? 'Void this realized' : 'Archive this pending'} ${sale.itemName}? The original financial evidence will remain preserved.`)) return; const correctionReason = sale.status === 'charged' ? window.prompt('Enter the correction reason for voiding this realized transaction.')?.trim() || '' : ''; if (sale.status === 'charged' && !correctionReason) return; try { saved(await wineSpiritsApi.archive(sale.id, correctionReason)); onToast('Wine / Spirit sale archived.') } catch (cause) { onToast(cause instanceof Error ? cause.message : 'Unable to archive the sale.') } }
  return <section className="wine-page">
    <header className="wine-toolbar">
      <div><p className="eyebrow">FINANCIAL PROOF · MANUAL ENTRY</p><h2>Wine &amp; Spirits Sales</h2><p>Record signed-check sales using exact Symphony evidence. Incentives remain provisional.</p></div>
      <div><label>Month<input type="month" value={month} onChange={event => setMonth(event.target.value)} /></label><button className="primary" type="button" onClick={() => setEditing('new')}>＋ Add Wine / Spirit Sale</button></div>
    </header>
    <section className="panel wine-panel">
      <div className="wine-filters"><input aria-label="Search Wine and Spirits sales" placeholder="Search check, room, bottle, table or waiter" value={query} onChange={event => setQuery(event.target.value)} /><select aria-label="Filter by waiter" value={waiter} onChange={event => setWaiter(event.target.value)}><option value="all">All waiters</option>{staff.map(person => <option key={person.id} value={person.id}>{person.name} · {person.number}</option>)}</select><select aria-label="Filter by status" value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="all">All statuses</option>{statuses.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select><label className="check-label"><input type="checkbox" checked={showArchived} onChange={event => setShowArchived(event.target.checked)} /> Show archived</label></div>
      {loading && <div className="inline-state">Loading Wine/Spirits sales…</div>}
      {error && <div className="inline-state error-state"><p>{error}</p><button className="secondary" onClick={() => void load()}>Try again</button></div>}
      {!loading && !error && <div className="wine-table-wrap" tabIndex={0}><table className="wine-table"><thead><tr><th>Date</th><th>Check / Invoice</th><th>Room</th><th>Table</th><th>Bottle / Item</th><th>Waiter</th><th>Qty</th><th>Gross Unit</th><th>Net Unit</th><th>Applied Tier</th><th>Incentive</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(sale => <tr key={sale.id} className={sale.archived ? 'archived-row' : ''}><td>{sale.serviceDate}</td><td><b>{sale.checkInvoiceNumber}</b></td><td>{sale.roomNumber}</td><td>{sale.tableNumber}</td><td className="wine-name"><b>{sale.itemName}</b></td><td><b>{sale.waiter.name}</b><small>{sale.waiter.number}</small></td><td>{sale.quantity}</td><td>{money(sale.grossUnitPrice)}</td><td>{money(sale.netUnitPrice)}</td><td>{sale.appliedTier}</td><td><b>{sale.status === 'charged' && !sale.archived ? money(sale.totalIncentive) : '$0.00'}</b></td><td><span className={`wine-status ${sale.status}`}>{sale.archived ? 'Archived' : statusLabel(sale.status)}</span></td><td className="row-actions"><button className="link" onClick={() => setViewing(sale)}>View</button>{!sale.archived && sale.status === 'pending' && <button className="link" onClick={() => setEditing(sale)}>Edit</button>}{!sale.archived && !['cancelled','void'].includes(sale.status) && <button className="link danger" onClick={() => void archive(sale)}>{sale.status === 'charged' ? 'Void' : 'Archive'}</button>}</td></tr>)}</tbody></table>
      <div className="wine-mobile-list">{visible.map(sale => <article key={sale.id} className={`mobile-operation-card${sale.archived ? ' archived-row' : ''}`}><header><div><span className="mobile-card-kicker">{sale.checkInvoiceNumber}</span><h4>{sale.itemName}</h4><small>{sale.serviceDate} · Room {sale.roomNumber} · {sale.tableNumber}</small></div><strong>{sale.status === 'charged' && !sale.archived ? money(sale.totalIncentive) : '$0.00'}</strong></header><div className="mobile-card-facts"><span><small>Sold by</small><b>{sale.waiter.name}</b></span><span><small>Qty</small><b>{sale.quantity}</b></span><span><small>Status</small><b>{sale.archived ? 'Archived' : statusLabel(sale.status)}</b></span></div><div className="mobile-card-actions"><button className="secondary" onClick={() => setViewing(sale)}>View</button>{!sale.archived && sale.status === 'pending' && <button className="secondary" onClick={() => setEditing(sale)}>Edit</button>}{!sale.archived && !['cancelled','void'].includes(sale.status) && <button className="secondary danger" onClick={() => void archive(sale)}>{sale.status === 'charged' ? 'Void' : 'Archive'}</button>}</div></article>)}</div>
      {visible.length === 0 && <div className="inline-empty">No Wine/Spirits sales match this period and filters.</div>}</div>}
    </section>
    {editing && <WineSaleForm sale={editing === 'new' ? undefined : editing} staff={staff} tables={tables} onClose={() => setEditing(null)} onSave={async input => { const result = editing === 'new' ? await wineSpiritsApi.create(input) : await wineSpiritsApi.update(input); saved(result); setEditing(null); onToast('Wine / Spirit sale saved.') }} />}
    {viewing && <WineSaleDetails sale={viewing} onClose={() => setViewing(null)} onEdit={() => { setEditing(viewing); setViewing(null) }} />}
  </section>
}

function WineSaleForm({ sale, staff, tables, onClose, onSave }: { sale?: WineSpiritSale; staff: Staff[]; tables: ConfigOption[]; onClose: () => void; onSave: (input: WineSpiritSaleInput) => Promise<void> }) {
  const eligible = staff.filter(person => (person.assignmentEligible && person.serviceAssignmentEligible) || person.id === sale?.waiterId)
  const [form, setForm] = useState<WineSpiritSaleInput>(sale ? toInput(sale) : { id: crypto.randomUUID(), serviceDate: serviceDate(), checkInvoiceNumber: '', itemName: '', roomNumber: '', tableNumber: '', waiterId: '', grossUnitPrice: '', quantity: 1, status: 'pending', notes: '' })
  const [calculation, setCalculation] = useState<WineSpiritCalculation | null>(sale || null)
  const [calculationError, setCalculationError] = useState('')
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const [duplicates, setDuplicates] = useState<Array<{ id: string; checkInvoiceNumber: string; itemName: string }>>([])
  const [duplicateApproved, setDuplicateApproved] = useState(false)
  const update = <K extends keyof WineSpiritSaleInput>(key: K, value: WineSpiritSaleInput[K]) => { setForm(current => ({ ...current, [key]: value })); setDuplicateApproved(false); setDuplicates([]) }
  useEffect(() => { const valid = form.serviceDate && Number(form.grossUnitPrice) > 0 && Number.isInteger(form.quantity) && form.quantity > 0; if (!valid) { setCalculation(null); setCalculationError(''); return }; const timer = window.setTimeout(() => { wineSpiritsApi.calculate(form).then(value => { setCalculation(value); setCalculationError('') }).catch(cause => { setCalculation(null); setCalculationError(cause instanceof Error ? cause.message : 'Calculation unavailable.') }) }, 220); return () => window.clearTimeout(timer) }, [form.serviceDate, form.grossUnitPrice, form.quantity])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.serviceDate || !form.checkInvoiceNumber.trim() || !form.roomNumber.trim() || !form.tableNumber.trim() || !form.itemName.trim() || !form.waiterId || Number(form.grossUnitPrice) <= 0 || form.quantity < 1) return setError('Complete every highlighted financial-proof field before saving.'); if (!calculation) return setError(calculationError || 'Wait for the authoritative calculation before saving.'); setSaving(true); setError(''); try { if (!duplicateApproved) { const matches = await wineSpiritsApi.duplicateReview(form); if (matches.length) { setDuplicates(matches); setSaving(false); return } }; await onSave(form) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save the Wine/Spirits sale.') } finally { setSaving(false) } }
  return <div className="modal-backdrop"><section className="modal booking-modal-wide wine-modal" role="dialog" aria-modal="true" aria-label={sale ? 'Edit Wine or Spirit Sale' : 'Add Wine or Spirit Sale'}><button type="button" className="close" aria-label="Close" onClick={onClose}>×</button><h2>{sale ? 'Edit Wine / Spirit Sale' : 'Add Wine / Spirit Sale'}</h2><p className="wine-form-intro">Financial-proof fields should match the guest-signed Symphony check exactly.</p><form className="staff-form" onSubmit={event => void submit(event)}>
    <fieldset><legend>Signed Check Evidence</legend><div className="wine-form-grid"><label>Service Date<input required type="date" value={form.serviceDate} onChange={event => update('serviceDate', event.target.value)} /></label><label>Check / Invoice Number<input required value={form.checkInvoiceNumber} onChange={event => update('checkInvoiceNumber', event.target.value)} /></label><label>Room Number<input required value={form.roomNumber} onChange={event => update('roomNumber', event.target.value)} /></label><label>Table Number<select required value={form.tableNumber} onChange={event => update('tableNumber', event.target.value)}><option value="">Select table</option>{tables.filter(option => option.active || option.value === form.tableNumber).map(option => <option key={option.id} value={option.value}>{option.label}</option>)}</select></label><label className="wine-wide">Exact Bottle / Item Name<input required value={form.itemName} onChange={event => update('itemName', event.target.value)} /><small>Enter exactly as shown on the signed check.</small></label><label>Waiter / Sold By<select required value={form.waiterId} onChange={event => update('waiterId', event.target.value)}><option value="">Select Staff</option>{eligible.map(person => <option key={person.id} value={person.id} disabled={!person.assignmentEligible || !person.serviceAssignmentEligible}>{person.name} · {person.number}{!person.assignmentEligible ? ' (Inactive — historical)' : ''}</option>)}</select></label><label>Gross Symphony Selling Price<input required type="number" min="0.01" step="0.01" inputMode="decimal" value={form.grossUnitPrice} onChange={event => update('grossUnitPrice', event.target.value)} /></label><label>Quantity<input required type="number" min="1" step="1" value={form.quantity} onChange={event => update('quantity', Number(event.target.value))} /></label><label>Status<select value={form.status} onChange={event => update('status', event.target.value as WineSpiritSaleStatus)}>{statuses.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div></fieldset>
    <fieldset><legend>Authoritative Calculation</legend>{calculation ? <div className="wine-calculation"><Calc label="Gross Unit Price" value={money(calculation.grossUnitPrice)} /><Calc label="Gross Total" value={money(calculation.grossTotal)} /><Calc label="Net Unit Price" value={money(calculation.netUnitPrice)} /><Calc label="Applied Tier" value={calculation.appliedTier} /><Calc label="Incentive / Bottle" value={money(calculation.incentivePerBottle)} /><Calc label="Quantity" value={String(form.quantity)} /><Calc label="Total Incentive" value={form.status === 'charged' ? money(calculation.totalIncentive) : '$0.00 contributing'} /></div> : <p className="wine-calculation-empty">Enter a valid Service Date, gross unit price and quantity to calculate.</p>}{calculationError && <p className="save-error">{calculationError}</p>}</fieldset>
    <label>Notes<textarea rows={3} value={form.notes} onChange={event => update('notes', event.target.value)} placeholder="Optional manager note" /></label>
    {duplicates.length > 0 && <div className="wine-duplicate-warning"><b>Possible duplicate — manager review required</b><p>An existing transaction has the same date, check, room, item, waiter, price, quantity and table. Multiple items or bottles can be legitimate.</p>{duplicates.map(item => <small key={item.id}>{item.checkInvoiceNumber} · {item.itemName}</small>)}<label className="check-label"><input type="checkbox" checked={duplicateApproved} onChange={event => setDuplicateApproved(event.target.checked)} /> I reviewed this warning and want to save this legitimate transaction.</label></div>}
    {error && <p className="save-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving || (duplicates.length > 0 && !duplicateApproved)}>{saving ? 'Saving…' : 'Save Wine / Spirit Sale'}</button></div>
  </form></section></div>
}

function Calc({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div> }

function WineSaleDetails({ sale, onClose, onEdit }: { sale: WineSpiritSale; onClose: () => void; onEdit: () => void }) {
  const [audit, setAudit] = useState<Array<{ id: string; action: string; actor: string; createdAt: string }>>([])
  useEffect(() => { void wineSpiritsApi.audit(sale.id).then(setAudit).catch(() => setAudit([])); const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [sale.id, onClose])
  const detail = (label: string, value: string, key?: string) => <div key={key}><span>{label}</span><b>{value}</b></div>
  return <div className="chargeable-drawer-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><aside className="chargeable-drawer wine-drawer" role="dialog" aria-modal="true" aria-label="Wine and Spirit Sale Details"><header><div><p className="eyebrow">FINANCIAL PROOF CHAIN</p><h2>{sale.itemName}</h2><span className={`wine-status ${sale.status}`}>{sale.archived ? 'Archived' : statusLabel(sale.status)}</span></div><button className="close" aria-label="Close" onClick={onClose}>×</button></header><div className="chargeable-drawer-body"><section><h3>Signed Check Evidence</h3>{detail('Service Date', sale.serviceDate)}{detail('Check / Invoice', sale.checkInvoiceNumber)}{detail('Room', sale.roomNumber)}{detail('Table', sale.tableNumber)}{detail('Bottle / Item', sale.itemName)}{detail('Waiter', `${sale.waiter.name} · ${sale.waiter.number}`)}</section><section><h3>Authoritative Calculation</h3>{detail('Gross Unit Price', money(sale.grossUnitPrice))}{detail('Quantity', String(sale.quantity))}{detail('Gross Total', money(sale.grossTotal))}{detail('Service Charge', `${sale.serviceChargeRate}%`)}{detail('GST', `${sale.gstRate}%`)}{detail('Net Unit Price', money(sale.netUnitPrice))}{detail('Net Total', money(sale.netTotal))}{detail('Applied Tier', sale.appliedTier)}{detail('Incentive / Bottle', money(sale.incentivePerBottle))}{detail('Total Incentive', sale.status === 'charged' && !sale.archived ? money(sale.totalIncentive) : '$0.00 contributing')}</section><section><h3>Record &amp; Audit</h3>{detail('Outlet', 'Andalucía')}{detail('Notes', sale.notes || '—')}{detail('Created', `${new Date(sale.createdAt).toLocaleString()} · ${sale.createdBy}`)}{detail('Updated', `${new Date(sale.updatedAt).toLocaleString()} · ${sale.updatedBy}`)}{audit.map(item => detail(item.action.replaceAll('_', ' '), `${new Date(item.createdAt).toLocaleString()} · ${item.actor}`, item.id))}</section></div>{!sale.archived && sale.status === 'pending' && <footer><button className="secondary" onClick={onEdit}>Edit Sale</button></footer>}</aside></div>
}
